'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const splitSentences=text=>String(text||'').replace(/\r/g,'\n').split(/\n+|(?<=[.!?;])\s+/).map(x=>x.trim()).filter(Boolean);
let currentReport={}, fullReport={}, currentType='first', lastInput='', presentationSlides=[], slideIndex=0, currentGroupSession=null, recognition=null, isDictating=false, compactMode=false;
let wakeLock=null, dictationWanted=false, restartTimer=null, draftTimer=null;
const DRAFT_KEY='psikiaHubDraftV21';

const labels={
 first:'Primera consulta',follow:'Consulta de seguimiento',acute:'Consulta en agudos',urInitial:'UR · valoración/ingreso',urFollow:'UR · seguimiento',pti:'UR · PTI',discharge:'UR · alta',emergency:'Urgencias'
};
const sections={
 first:['Motivo de consulta / derivación','Antecedentes médicos no psiquiátricos','Antecedentes psiquiátricos personales','Antecedentes familiares psiquiátricos','Consumo de sustancias','Situación sociolaboral y funcional','Tratamiento actual','Enfermedad actual / evolución longitudinal','Exploración psicopatológica','Juicio clínico','Plan de tratamiento','Seguimiento'],
 urInitial:['Motivo de derivación / ingreso','Antecedentes médicos no psiquiátricos','Antecedentes psiquiátricos y de consumo','Antecedentes familiares psiquiátricos','Situación sociolaboral y funcional','Tratamiento actual','Enfermedad actual / evolución longitudinal','Exploración psicopatológica','Juicio clínico','Plan de tratamiento e intervención','Disposición / ingreso'],
 follow:['Resumen clínico','Evolución desde la última revisión','Exploración psicopatológica comparativa','Juicio clínico','Plan de tratamiento','Próxima cita'],
 urFollow:['Resumen clínico y funcional','Evolución clínica','Evolución funcional / rehabilitadora','Exploración psicopatológica comparativa','Juicio clínico','Plan de intervención','Próxima revisión'],
 acute:['Motivo de consulta','Resumen de antecedentes relevantes','Enfermedad actual / situación precipitante','Exploración psicopatológica','Juicio clínico','Intervención realizada','Plan / seguimiento'],
 emergency:['Motivo de consulta','Antecedentes relevantes','Situación precipitante / enfermedad actual','Exploración psicopatológica','Valoración de riesgo','Pruebas / actuaciones realizadas','Juicio clínico','Tratamiento / intervención','Disposición y plan inmediato'],
 pti:['Resumen clínico y funcional','Necesidades / problemas activos','Objetivos del ingreso','Intervención de Psiquiatría','Intervención de Psicología','Intervención de Enfermería','Intervención de Terapia Ocupacional','Intervención de Trabajo Social','Otras intervenciones / coordinación','Indicadores de seguimiento'],
 discharge:['Motivo y contexto del ingreso','Antecedentes relevantes','Evolución durante el ingreso','Intervenciones realizadas','Exploración psicopatológica al alta','Diagnóstico al alta','Tratamiento al alta','Situación funcional al alta','Plan de seguimiento y recursos','Objetivos pendientes / recomendaciones']
};

const cues={
 'Motivo de consulta / derivación':['motivo','derivad','primera cita','consulta por','remitid'],
 'Motivo de derivación / ingreso':['motivo','derivad','ingreso','unidad de rehabilitacion'],
 'Motivo de consulta':['motivo','acude','consulta por','derivad'],
 'Antecedentes médicos no psiquiátricos':['antecedentes medicos','somatic','quirurg','alerg','diabetes','hipertension','renal','hepatic','cardiop'],
 'Antecedentes psiquiátricos personales':['antecedentes psiqui','episodios previos','salud mental','ingreso previo','tratamiento previo'],
 'Antecedentes psiquiátricos y de consumo':['antecedentes psiqui','episodios previos','consumo','cannabis','alcohol','cocaina','abstinencia','tratamientos previos'],
 'Antecedentes familiares psiquiátricos':['antecedentes familiares','hermana','hermano','madre','padre','familiares'],
 'Consumo de sustancias':['consumo','cannabis','alcohol','cocaina','opiace','tabaco','toxic','abstinencia'],
 'Situación sociolaboral y funcional':['trabaja','paro','desemple','casad','hijos','pareja','convive','autocuidado','ocupacional','actividad','aislamiento','social','laboral','cuadrilla'],
 'Tratamiento actual':['tratamiento actual','tratamiento farmac','mg','miligr','escitalopram','fluoxetina','mirtazapina','lorazepam','sertralina','venlafaxina','duloxetina','vortioxetina','aripiprazol','olanzapina','risperidona','paliperidona','quetiapina','clozapina','litio','valproato','lamotrigina'],
 'Enfermedad actual / evolución longitudinal':['enfermedad actual','desde hace','a raiz','progresivamente','ultimos','meses','semanas','inicio','empeora','crisis','desencaden','actualmente'],
 'Enfermedad actual / situación precipitante':['situacion precipitante','a raiz','desde hace','actualmente','crisis','empeora','inicio'],
 'Situación precipitante / enfermedad actual':['situacion precipitante','a raiz','desde hace','actualmente','crisis','empeora','inicio'],
 'Exploración psicopatológica':['exploracion','consciente','orientad','contacto','discurso','hipotimia','eutimia','ansiedad','delir','alucin','ideacion','planes de futuro','sueño','apetito','abulia','anhedonia'],
 'Juicio clínico':['juicio clinico','diagnost','impresion clinica','compatible con','se mantiene'],
 'Plan de tratamiento':['plan de tratamiento','indicamos','recomendamos','mantener','retirar','iniciar','pauta','enfermer','psicolog','relajacion','intervencion'],
 'Seguimiento':['cita','revision','seguimiento','meses','semanas'],
 'Intervención realizada':['intervencion','pautamos','recomendamos','administramos','psicoeduc','relajacion','tratamiento'],
 'Plan / seguimiento':['cita','seguimiento','revision','mantener','retirar','deriv'],
 'Valoración de riesgo':['riesgo','autolit','suicid','heteroagres','autoagres','planificad','intento'],
 'Pruebas / actuaciones realizadas':['analit','ecg','electrocard','tac','resonancia','observacion','medicacion administrada'],
 'Tratamiento / intervención':['tratamiento','intervencion','administramos','pautamos','psicoeduc'],
 'Disposición y plan inmediato':['alta','ingreso','observacion','deriv','seguimiento','acompañad','cita'],
 'Evolución desde la última revisión':['desde la ultima','ha mejorado','ha empeorado','progresos','persiste','respuesta','tolerado','evolucion'],
 'Evolución clínica':['desde la ultima','ha mejorado','ha empeorado','evolucion','sintomas','respuesta'],
 'Evolución funcional / rehabilitadora':['autocuidado','actividad','grupo','ocupacional','social','funcional','avd','salida','cuadrilla','deporte'],
 'Exploración psicopatológica comparativa':['exploracion','consciente','orientad','discurso','crisis','afect','futuro','sueño','apetito','delir','alucin','ideacion'],
 'Plan de intervención':['mantener','retirar','iniciar','tratamiento','psicolog','enfermer','terapia ocupacional','trabajo social','objetivo','intervencion'],
 'Próxima cita':['cita','revision','seguimiento','meses','semanas'],
 'Próxima revisión':['cita','revision','seguimiento','meses','semanas']
};

function score(section,s){
 const n=norm(s);let total=(cues[section]||[]).reduce((a,k)=>a+(n.includes(norm(k))?1:0),0), t=norm(section);
 if(/juicio clinico/.test(t)&&/\bjuicio\b|diagnost|impresion clinica/.test(n))total+=6;
 if(/plan de tratamiento|plan \/ seguimiento|plan de intervencion|tratamiento \/ intervencion/.test(t)&&/plan de tratamiento|\bplan\b|indicamos|mantenemos|retiramos|iniciamos|intervencion/.test(n))total+=4;
 if(/exploracion psicopatologica/.test(t)&&/delir|alucin|autolit|suicid|orientad|discurso|afect|hipotim|eutim|planes de futuro|duerme|sueño|apetito|come bien/.test(n))total+=3;
 if(/tratamiento actual/.test(t)&&/\bmg\b|miligr|escitalopram|fluoxetina|mirtazapina|lorazepam|sertralina|venlafaxina|duloxetina|vortioxetina|aripiprazol|olanzapina|risperidona|paliperidona|quetiapina|clozapina|litio|valproato|lamotrigina/.test(n))total+=3;
 if(/seguimiento|proxima cita|proxima revision/.test(t)&&/cita|revision|seguimiento|dentro de \d+|en \d+ (?:mes|seman)/.test(n))total+=4;
 return total;
}
function dedupe(arr){const seen=new Set();return arr.filter(x=>{const k=norm(x).replace(/[^a-z0-9]+/g,' ').trim();if(!k||seen.has(k))return false;seen.add(k);return true})}
function smartSegments(text){
 let s=String(text||'').replace(/\r/g,' ').replace(/\s+/g,' ').trim();if(!s)return [];
 const pivots=[
  /\s+(?=(?:un\s+)?juicio(?:\s+cl[ií]nico)?\b)/ig,
  /\s+(?=(?:el\s+)?plan de tratamiento\b)/ig,
  /\s+(?=tratamiento actual\b)/ig,
  /\s+(?=enfermedad actual\b)/ig,
  /\s+(?=exploraci[oó]n psicopatol[oó]gica\b)/ig,
  /\s+(?=motivo de (?:consulta|derivaci[oó]n)\b)/ig,
  /\s+(?=antecedentes (?:m[eé]dicos|psiqui[aá]tricos|familiares)\b)/ig,
  /\s+(?=consumo de sustancias\b)/ig,
  /\s+(?=(?:pr[oó]xima\s+)?cita\b)/ig,
  /\s+(?=seguimiento\b)/ig
 ];
 pivots.forEach(re=>{s=s.replace(re,' ||| ')});
 let chunks=s.split(/\s*\|\|\|\s*|\n+|(?<=[.!?;])\s+/).map(x=>x.trim()).filter(x=>x&&!/^(?:un|una|el|la)$/i.test(x)), out=[];
 for(const c of chunks){
  if(c.split(/\s+/).length>34){
   const subs=c.split(/\s+(?:y|pero|aunque)\s+(?=(?:actualmente|refiere|presenta|no presenta|no tiene|parece|se mantiene|hacemos|indicamos|retiramos|mantenemos|cita|juicio|plan)\b)/i).map(x=>x.trim()).filter(Boolean);
   out.push(...subs);
  }else out.push(c);
 }
 return out;
}
function classify(text, list){
 const out=Object.fromEntries(list.map(s=>[s,[]]));
 smartSegments(text).forEach(sent=>{let best=list[0],max=0;list.forEach(sec=>{const sc=score(sec,sent);if(sc>max){max=sc;best=sec}});if(max===0){best=list.find(x=>/Enfermedad|Evolución/.test(x))||list[0]}out[best].push(sent)});
 return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,dedupe(v).join(' ')]));
}

function patientStore(){try{return JSON.parse(localStorage.getItem('psikiaPatientsV2')||'{}')}catch{return {}}}
function savePatientStore(obj){localStorage.setItem('psikiaPatientsV2',JSON.stringify(obj))}
function getCode(){return ($('#patientCode').value||'').trim().toUpperCase().replace(/[^A-ZÁÉÍÓÚÑ]/g,'').slice(0,2)}
function getContext(code=getCode()){return code?patientStore()[code]||null:null}
function updateContextHint(){const code=getCode(), c=getContext(code);$('#patientCode').value=code;$('#contextDot').classList.toggle('on',!!c);$('#contextHint').textContent=!code?'Introduce 1–2 letras si quieres continuidad local.':c?`Contexto previo de ${code} cargado · ${new Date(c.updated).toLocaleDateString('es-ES')}`:`Sin contexto previo para ${code}.`}

function contextSummary(c){return c?.summary||''}
function extractExplicitDiagnosis(text){const s=splitSentences(text).filter(x=>/juicio clinico|diagnostico|diagnóstico|compatible con/i.test(x));return s.join(' ')}
function buildFollow(text,type){const base=classify(text,sections[type]);const c=getContext();if(type==='follow'){base['Resumen clínico']=contextSummary(c)||'Sin resumen previo guardado.'}else{base['Resumen clínico y funcional']=contextSummary(c)||'Sin resumen previo guardado.'}return base}
function buildPTI(text){const c=contextSummary(getContext()), n=norm(`${c} ${text}`), goals=[];
 if(/depres|hipotim|anhed|apat|abul/.test(n))goals.push('Mejorar la sintomatología afectiva y recuperar actividad gratificante.');
 if(/autocuidado|higiene|avd/.test(n))goals.push('Mejorar autonomía y regularidad en autocuidado y actividades de la vida diaria.');
 if(/aisla|social|cuadrilla|interaccion/.test(n))goals.push('Incrementar participación social y reducir aislamiento.');
 if(/ocupacional|trabaj|empleo|actividad/.test(n))goals.push('Recuperar estructura ocupacional y avanzar hacia objetivos laborales realistas.');
 if(/psicos|delir|alucin/.test(n))goals.push('Mejorar afrontamiento, flexibilidad cognitiva y funcionamiento asociado a la clínica psicótica.');
 if(/consumo|cannabis|alcohol|cocaina/.test(n))goals.push('Reforzar motivación, reducción de riesgos y prevención de recaídas.');
 if(/autolit|suicid|autoagres/.test(n))goals.push('Monitorizar riesgo y consolidar estrategias de seguridad y afrontamiento.');
 if(!goals.length)goals.push('Mejorar funcionamiento global y avanzar en objetivos rehabilitadores individualizados.');
 return {
  'Resumen clínico y funcional':c||text,
  'Necesidades / problemas activos':splitSentences(text).filter(x=>/problema|dificult|deterior|aisla|autocuidado|sintom|riesgo|consumo|ocupacional|social/i.test(x)).join(' ')||'A concretar con el equipo a partir de la valoración funcional.',
  'Objetivos del ingreso':goals.map(x=>'• '+x).join('\n'),
  'Intervención de Psiquiatría':'Revisión de evolución clínica, tolerancia y respuesta al tratamiento; optimización farmacológica si procede y monitorización de riesgos.',
  'Intervención de Psicología':'Intervención individual/grupal orientada a formulación, psicoeducación, estrategias cognitivo-conductuales y objetivos funcionales según necesidades.',
  'Intervención de Enfermería':'Seguimiento clínico, adherencia, autocuidados, hábitos, educación sanitaria y entrenamiento de habilidades aplicables a la vida diaria.',
  'Intervención de Terapia Ocupacional':'Activación, estructuración de rutinas, actividades significativas, autonomía y objetivos ocupacionales.',
  'Intervención de Trabajo Social':'Valoración de red de apoyo, situación social/laboral y recursos comunitarios pertinentes.',
  'Otras intervenciones / coordinación':'Coordinación con dispositivos y recursos externos cuando resulte indicado.',
  'Indicadores de seguimiento':'Revisar evolución sintomática, funcionamiento, participación, adherencia y grado de consecución de los objetivos acordados.'
 };
}
function buildDischarge(text){const out=classify(text,sections.discharge);const c=contextSummary(getContext());if(!out['Antecedentes relevantes'])out['Antecedentes relevantes']=c;if(!out['Motivo y contexto del ingreso'])out['Motivo y contexto del ingreso']=c;return out}
function buildReport(text,type){if(['follow','urFollow'].includes(type))return buildFollow(text,type);if(type==='pti')return buildPTI(text);if(type==='discharge')return buildDischarge(text);return classify(text,sections[type]||sections.first)}
function wordCount(text){return String(text||'').trim().split(/\s+/).filter(Boolean).length}
function firstValue(rep,keys){for(const k of keys){if(String(rep[k]||'').trim())return rep[k]}return ''}
function joinValues(rep,keys){return keys.map(k=>String(rep[k]||'').trim()).filter(Boolean).join(' ')}
function shouldCompact(text,type){if(['follow','urFollow'].includes(type))return true;if(['pti','discharge','emergency','urInitial'].includes(type))return false;return wordCount(text)<=145}
function compactReport(rep,type){
 if(type==='follow')return {
  'Descripción del caso':rep['Resumen clínico']||'',
  'Evolución':rep['Evolución desde la última revisión']||'',
  'Exploración psicopatológica':rep['Exploración psicopatológica comparativa']||'',
  'Juicio clínico':rep['Juicio clínico']||'',
  'Plan y seguimiento':joinValues(rep,['Plan de tratamiento','Próxima cita'])
 };
 if(type==='urFollow')return {
  'Descripción del caso':rep['Resumen clínico y funcional']||'',
  'Evolución clínica y funcional':joinValues(rep,['Evolución clínica','Evolución funcional / rehabilitadora']),
  'Exploración psicopatológica':rep['Exploración psicopatológica comparativa']||'',
  'Juicio clínico':rep['Juicio clínico']||'',
  'Plan y seguimiento':joinValues(rep,['Plan de intervención','Próxima revisión'])
 };
 if(type==='first')return {
  'Motivo de consulta / derivación':rep['Motivo de consulta / derivación']||'',
  'Descripción del caso':joinValues(rep,['Antecedentes médicos no psiquiátricos','Antecedentes psiquiátricos personales','Antecedentes familiares psiquiátricos','Consumo de sustancias','Situación sociolaboral y funcional','Tratamiento actual']),
  'Enfermedad actual / evolución':rep['Enfermedad actual / evolución longitudinal']||'',
  'Exploración psicopatológica':rep['Exploración psicopatológica']||'',
  'Juicio clínico':rep['Juicio clínico']||'',
  'Plan y seguimiento':joinValues(rep,['Plan de tratamiento','Seguimiento'])
 };
 if(type==='acute')return {
  'Motivo de consulta':rep['Motivo de consulta']||'',
  'Descripción del caso':rep['Resumen de antecedentes relevantes']||'',
  'Evolución / situación actual':rep['Enfermedad actual / situación precipitante']||'',
  'Exploración psicopatológica':rep['Exploración psicopatológica']||'',
  'Juicio clínico':rep['Juicio clínico']||'',
  'Intervención y seguimiento':joinValues(rep,['Intervención realizada','Plan / seguimiento'])
 };
 return {...rep};
}
function reportSectionHtml(sec,val){return `<div class="reportSection"><div class="reportTitle">${esc(sec)}</div><div class="reportText ${val?'':'empty'}" contenteditable="true" data-sec="${esc(sec)}">${esc(val||'')}</div></div>`}
function renderReport(){
 const list=Object.keys(currentReport), filled=list.filter(sec=>String(currentReport[sec]||'').trim()), empty=list.filter(sec=>!String(currentReport[sec]||'').trim());
 $('#reportHeading').textContent=labels[currentType]||'Nota clínica';
 $('#formatBadge').textContent=compactMode?'Formato breve automático':'Formato completo automático';
 $('#report').innerHTML=(filled.length?filled.map(sec=>reportSectionHtml(sec,currentReport[sec])).join(''):'<div class="small">No se ha podido asignar contenido todavía.</div>')+(empty.length?`<details class="emptySections"><summary>Apartados sin contenido (${empty.length})</summary><div class="detailBody">${empty.map(sec=>reportSectionHtml(sec,'')).join('')}</div></details>`:'');
 $$('.reportText').forEach(el=>el.addEventListener('input',()=>{currentReport[el.dataset.sec]=el.textContent.trim();if(Object.prototype.hasOwnProperty.call(fullReport,el.dataset.sec))fullReport[el.dataset.sec]=currentReport[el.dataset.sec];el.classList.toggle('empty',!currentReport[el.dataset.sec])}));
 $('#diagnosticSuggestion').innerHTML=diagnosticHtml(lastInput,currentReport);$('#therapySuggestion').innerHTML=therapyHtml(`${lastInput} ${reportText()}`);$('#resultCard').hidden=false;$('#resultCard').scrollIntoView({behavior:'smooth',block:'start'});
}
function reportText(){return Object.entries(currentReport).filter(([,v])=>String(v||'').trim()).map(([k,v])=>`${k.toUpperCase()}\n${String(v).trim()}`).join('\n\n')}
function suggestionText(id){return [...document.querySelectorAll(`#${id} .suggestionBox`)].map(x=>x.innerText.trim()).filter(Boolean).join('\n')}
function appendText(obj,key,prefix,text){if(!text)return false;const clean=String(text).replace(/\n+/g,' ').trim(), existing=String(obj[key]||'').trim();if(existing.includes(clean))return false;obj[key]=[existing,`${prefix}${clean}`].filter(Boolean).join(' ');return true}
function diagnosticTarget(rep){return Object.keys(rep).find(k=>/Diagnóstico al alta|Juicio clínico|Diagnóstico/i.test(k))||'Juicio clínico'}
function therapyTarget(rep){return Object.keys(rep).find(k=>/Intervención de Psicología|Plan de tratamiento e intervención|Plan de tratamiento|Plan de intervención|Tratamiento \/ intervención|Intervención realizada|Intervención y seguimiento|Plan y seguimiento/i.test(k))||'Plan de tratamiento'}
function addDiagnosticToDocument(){const t=suggestionText('diagnosticSuggestion');if(!t)return alert('No hay orientación diagnóstica concreta para añadir.');const key=diagnosticTarget(fullReport);appendText(fullReport,key,'Orientación diagnóstica: ',t);currentReport=compactMode?compactReport(fullReport,currentType):{...fullReport};renderReport();$('#diagnosticDetails').open=true;$('#saveHint').textContent='Orientación diagnóstica añadida al borrador. Revísala antes de enviar.'}
function addTherapyToDocument(){const t=suggestionText('therapySuggestion');if(!t)return alert('No hay intervención concreta para añadir.');const key=therapyTarget(fullReport);appendText(fullReport,key,'Intervención psicoterapéutica: ',t);currentReport=compactMode?compactReport(fullReport,currentType):{...fullReport};renderReport();$('#therapyDetails').open=true;$('#saveHint').textContent='Intervención psicoterapéutica añadida al borrador. Revísala antes de enviar.'}
function makeSummary(){const source=Object.keys(fullReport).length?fullReport:currentReport;const preferred=['Juicio clínico','Juicio clínico / diagnóstico','Diagnóstico al alta','Tratamiento actual','Tratamiento al alta','Plan de tratamiento','Plan de intervención','Evolución clínica','Evolución desde la última revisión','Situación sociolaboral y funcional'];const parts=[];preferred.forEach(k=>{if(source[k])parts.push(`${k}: ${source[k]}`)});if(!parts.length)parts.push(reportText().slice(0,1600));return parts.join(' ')}
function saveCurrentContext(){const code=getCode();if(!code)return $('#saveHint').textContent='Añade un código A/AB para guardar continuidad local.';const store=patientStore();store[code]={summary:makeSummary().slice(0,2200),updated:new Date().toISOString(),type:currentType};savePatientStore(store);updateContextHint();$('#saveHint').textContent=`Contexto de ${code} guardado localmente.`}

function diagnosticHtml(text,rep){const explicit=extractExplicitDiagnosis(text);const n=norm(`${text} ${reportText()}`);let lines=[];
 if(explicit)lines.push(`<div class="suggestionBox"><strong>Diagnóstico consignado en el dictado</strong><br>${esc(explicit)}</div>`);
 if(/agoraf|panico|crisis de angustia/.test(n))lines.push(`<div class="suggestionBox"><strong>Comprobar</strong><br>Valorar trastorno de pánico y/o agorafobia. Revisar si existen crisis inesperadas, cambio conductual persistente y duración de la evitación antes de fijar el código.</div>`);
 if(/depres|hipotim|anhed|abul|apatia/.test(n))lines.push(`<div class="suggestionBox"><strong>Comprobar</strong><br>Precisar duración del síndrome depresivo, número de síntomas, repercusión funcional, episodios previos y presencia/ausencia de síntomas psicóticos o maniformes antes de codificar.</div>`);
 if(/psicos|esquizof|delir|alucin/.test(n))lines.push(`<div class="suggestionBox"><strong>Comprobar</strong><br>Revisar temporalidad, síntomas positivos/negativos, afectivos, consumo de sustancias, funcionamiento y diagnósticos diferenciales antes de modificar el juicio clínico previo.</div>`);
 if(/bipolar|mania|maniaco|hipoman/.test(n))lines.push(`<div class="suggestionBox"><strong>Comprobar</strong><br>Precisar episodios maniformes/hipomaniformes, duración, repercusión y relación temporal con antidepresivos o sustancias.</div>`);
 if(!lines.length)lines.push(`<div class="small">No hay una diana diagnóstica clara extraíble del dictado. Si has consignado el juicio clínico, se mantiene como referencia para tu revisión.</div>`);
 return lines.join('');
}
function therapyHtml(text){const n=norm(text), ideas=[];
 if(/depres|anhed|apat|abul|aisla/.test(n))ideas.push(['Activación conductual','Definir una actividad pequeña, concreta y programable; anticipar barreras; registrar efecto sobre dominio/placer y revisar en la siguiente sesión.']);
 if(/panico|agoraf|crisis de angustia|evitacion/.test(n))ideas.push(['Pánico/agorafobia','Psicoeducar sobre el ciclo alarma–interpretación–evitación; construir una jerarquía de exposición gradual y acordar un primer paso manejable. La relajación puede usarse como habilidad complementaria, evitando convertirla en conducta de seguridad.']);
 if(/tension|relajacion|ansiedad flotante|nervios/.test(n))ideas.push(['Relajación muscular progresiva','Tensar de forma suave 5–7 segundos y soltar 15–20 segundos distintos grupos musculares, observando contraste tensión–distensión y evitando zonas dolorosas. Practicar inicialmente 10–15 minutos en contexto tranquilo.']);
 if(/psicos|esquizof|delir|parano|alucin/.test(n))ideas.push(['Metacognición / CBTp','Trabajar una situación concreta sin confrontar la creencia: separar hechos de interpretaciones, generar 2–3 explicaciones alternativas y estimar grado de certeza antes/después.']);
 if(/consumo|cannabis|alcohol|cocaina|craving/.test(n))ideas.push(['Entrevista motivacional / Matrix','Explorar ambivalencia, razones propias para el cambio, disparadores y una respuesta concreta ante una situación de alto riesgo.']);
 if(/limite|asert|dependen|sumis|conflicto interpersonal/.test(n))ideas.push(['Asertividad y límites','Ensayar una petición o negativa con estructura breve: describir situación, expresar necesidad, formular petición/límite y mantener el mensaje sin justificar en exceso.']);
 if(/tlp|borderline|desregul|impulsiv/.test(n))ideas.push(['Regulación emocional','Identificar emoción, intensidad, impulso y conducta; introducir una pausa y elegir una respuesta compatible con objetivos antes de actuar.']);
 if(/insom|sueño|despertar precoz/.test(n))ideas.push(['Sueño','Revisar regularidad horaria, tiempo en cama, siestas, activación nocturna y rutina de desaceleración; seleccionar uno o dos cambios observables.']);
 if(!ideas.length)ideas.push(['Intervención breve','Elegir un objetivo funcional concreto, formular qué mantiene la dificultad y ensayar una conducta alternativa verificable antes de la siguiente revisión.']);
 return ideas.slice(0,4).map(([t,d])=>`<div class="suggestionBox"><strong>${esc(t)}</strong><br>${esc(d)}</div>`).join('');
}


function setDictationStatus(msg){const el=$('#dictationStatus');if(el)el.textContent=msg}
function saveDraftNow(msg){
 try{localStorage.setItem(DRAFT_KEY,JSON.stringify({raw:$('#raw').value,code:getCode(),type:$('#visitType').value,updated:new Date().toISOString()}));if(msg)setDictationStatus(msg)}catch{}
}
function scheduleDraftSave(){clearTimeout(draftTimer);draftTimer=setTimeout(()=>saveDraftNow('Borrador guardado automáticamente.'),180)}
function restoreDraft(){
 try{const d=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null');if(!d||!d.raw)return;const age=Date.now()-new Date(d.updated).getTime();if(age>7*24*3600*1000)return;$('#raw').value=d.raw||'';if(d.code)$('#patientCode').value=d.code;if(d.type&&labels[d.type])$('#visitType').value=d.type;setDictationStatus('Borrador recuperado automáticamente. Puedes continuar dictando.')}catch{}
}
function clearDraft(){try{localStorage.removeItem(DRAFT_KEY)}catch{};setDictationStatus('Borrador nuevo. Guardado automático activo.')}
async function acquireWakeLock(){if(!('wakeLock' in navigator)||wakeLock)return;try{wakeLock=await navigator.wakeLock.request('screen');wakeLock.addEventListener('release',()=>{wakeLock=null})}catch{}}
async function releaseWakeLock(){if(wakeLock){try{await wakeLock.release()}catch{}wakeLock=null}}
function appendRecognized(text){const t=String(text||'').trim();if(!t)return;$('#raw').value=($('#raw').value.trim()+($('#raw').value.trim()?' ':'')+t).trim();saveDraftNow('Fragmento guardado · seguimos escuchando…')}
function stopDictation(message='Dictado detenido. El texto queda guardado.'){
 dictationWanted=false;isDictating=false;clearTimeout(restartTimer);if(recognition){try{recognition.stop()}catch{}recognition=null}releaseWakeLock();$('#dictate').textContent='🎙️ Dictar';setDictationStatus(message);saveDraftNow();
}
function startRecognitionLoop(){
 if(!dictationWanted||recognition)return;const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){dictationWanted=false;$('#raw').focus();setDictationStatus('Usa el micrófono del teclado: este navegador no ofrece dictado web.');return}
 const r=new SR();recognition=r;r.lang='es-ES';r.continuous=true;r.interimResults=true;isDictating=true;$('#dictate').textContent='⏹️ Detener dictado';acquireWakeLock();setDictationStatus('🎙️ Escuchando · pantalla activa · guardado automático.');
 r.onresult=e=>{let finalText='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const tr=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=tr+' ';else interim+=tr+' '}if(finalText)appendRecognized(finalText);if(interim)setDictationStatus('🎙️ Escuchando: '+interim.trim().slice(-90))};
 r.onerror=e=>{if(['not-allowed','service-not-allowed'].includes(e.error)){dictationWanted=false;setDictationStatus('Permiso de micrófono no disponible. Usa el micrófono del teclado.')}else if(e.error!=='aborted')setDictationStatus('El dictado se interrumpió; el texto reconocido sigue guardado.')};
 r.onend=()=>{if(recognition===r)recognition=null;isDictating=false;if(dictationWanted&&document.visibilityState==='visible'){restartTimer=setTimeout(startRecognitionLoop,300)}else{$('#dictate').textContent=dictationWanted?'🎙️ Reanudando…':'🎙️ Dictar';releaseWakeLock()}};
 try{r.start()}catch{recognition=null;restartTimer=setTimeout(startRecognitionLoop,500)}
}
function toggleDictation(){if(dictationWanted){stopDictation();return}dictationWanted=true;startRecognitionLoop()}

// ---- GROUPS ----
const groupCycles={
 assert:{name:'Asertividad y habilidades sociales',sessions:[
  {title:'1. Pasivo, agresivo, asertivo y manipulativo',duration:'60–70 min',concepts:[['Respuesta pasiva','No expresar la propia necesidad, ceder de forma habitual o evitar el conflicto aunque tenga un coste personal.'],['Respuesta agresiva','Defender la propia posición vulnerando o descalificando al otro, con amenaza, imposición o ataque.'],['Respuesta asertiva','Expresar una necesidad, opinión o límite de forma clara y respetuosa, aceptando que el otro puede no estar de acuerdo.'],['Respuesta manipulativa','Intentar obtener algo de forma indirecta mediante culpa, presión emocional, insinuación o mensajes ambiguos.']],
   caseTitle:'Caso: “Siempre acaba diciendo que sí”',caseText:'Mario lleva varios meses con ánimo bajo y tiende a evitar los conflictos. En su trabajo, un compañero le pide repetidamente que haga tareas adicionales que no forman parte de su turno. Mario acepta aunque sale más tarde y llega agotado a casa. Un día, tras varias semanas acumulando malestar, responde gritando: “¡Hazlo tú de una vez, que eres un aprovechado!”. Después se siente culpable y decide no volver a decir nada.',
   open:['¿Qué respuestas de Mario son pasivas y cuál es agresiva?','¿Qué necesidad legítima está intentando proteger?','¿Cómo podría haber intervenido antes de llegar al estallido?','¿Qué frase asertiva concreta podría utilizar mañana?'],
   quiz:{q:'Un compañero vuelve a pedirle que haga su tarea. ¿Cuál es la respuesta más asertiva?',options:['“Vale, no pasa nada”, aunque sabe que no puede asumirlo.','“Eres un vago. Siempre haces lo mismo.”','“Hoy no puedo hacer esa tarea. Necesito terminar la mía. Si hay que redistribuir trabajo, podemos hablarlo con el responsable.”','“Sí, claro… ya veo que algunos tienen mucha suerte”, esperando que capte la indirecta.'],correct:2,why:'La opción 3 describe la situación, pone un límite claro y propone una vía de solución sin atacar ni culpabilizar.'},
   dialogue:[['Terapeuta','¿Qué te dices justo antes de aceptar algo que no quieres hacer?'],['Paciente','Que si digo que no van a pensar que soy egoísta.'],['Terapeuta','¿Decir que no a una petición concreta significa necesariamente ser egoísta?'],['Paciente','No siempre, pero me cuesta tolerar que se molesten.'],['Terapeuta','Entonces quizá el objetivo no sea conseguir que nadie se moleste, sino aprender a mantener un límite aunque exista cierta incomodidad.']],
   pause:['¿Qué creencia mantiene la conducta pasiva?','¿Qué intenta cambiar el terapeuta: el pensamiento, la emoción o la conducta?','¿Qué frase alternativa podría ensayarse?'],
   exercise:'Role-play en tríadas. Persona A hace una petición excesiva; B practica una negativa breve; C observa si hubo claridad, respeto y exceso de justificación. Cambiar roles cada 3 minutos.',materials:['Tarjetas con 6 peticiones cotidianas ficticias','Hoja con cuatro estilos de respuesta','Reloj/temporizador de 3 minutos'],task:'Elegir una situación de bajo riesgo y preparar por escrito una frase asertiva de una o dos líneas.',slides:['¿Qué es ser asertivo?','Cuatro estilos de respuesta','Caso: Mario y las tareas extra','Pregunta al grupo: ¿qué harías tú?','Estructura de una respuesta asertiva','Role-play por tríadas']},
  {title:'2. Decir “no” sin justificar en exceso',duration:'60 min',concepts:[['Negativa asertiva','Respuesta clara y breve que reconoce la petición y mantiene el límite.'],['Disco rayado','Repetir el núcleo del límite con tono estable cuando aparecen presiones o nuevas justificaciones.']],caseTitle:'Caso: el favor que nunca termina',caseText:'Una amiga pide a Laura que la cubra por tercera vez en una actividad. Laura no quiere, pero teme decepcionarla. Empieza a inventar excusas complicadas y la conversación se convierte en una negociación interminable.',open:['¿Qué problema crea dar demasiadas explicaciones?','¿Cómo diferenciar una explicación razonable de una justificación defensiva?','¿Qué frase de “disco rayado” sería suficiente?'],quiz:{q:'¿Cuál sería una negativa más clara?',options:['“Ya veremos, quizá luego te digo.”','“No puedo esta vez. Entiendo que te venga mal, pero no voy a poder cubrirte.”','“Siempre me lo pides a mí.”','No responder al mensaje.'],correct:1,why:'Es clara, respetuosa y no abre una negociación falsa.'},dialogue:[['Terapeuta','Prueba a decir que no en una sola frase.'],['Paciente','No puedo porque esta semana estoy fatal, además…'],['Terapeuta','Para ahí. Ya tenemos suficiente. ¿Puedes repetir solo el límite?'],['Paciente','Esta vez no puedo cubrirte.'],['Terapeuta','Eso es. Ahora toleramos el silencio.']],pause:['¿Qué hace difícil el silencio después de decir no?','¿Qué emoción aparece y cuánto habría que tolerarla?'],exercise:'Ronda de negativas: cada persona recibe una tarjeta y responde en una sola frase. Segunda ronda: el interlocutor insiste y se practica repetir el límite.',materials:['Tarjetas de peticiones','Cronómetro'],task:'Practicar una negativa breve en contexto de bajo riesgo.',slides:['Decir no no es atacar','La trampa de justificar demasiado','Una frase clara','Cuando el otro insiste','Práctica']},
  {title:'3. Pedir lo que necesito',duration:'60 min',concepts:[['Petición concreta','Expresar qué conducta concreta se solicita, evitando esperar que el otro adivine la necesidad.']],caseTitle:'Caso: “Si me conociera, debería saberlo”',caseText:'David se enfada porque su pareja no le acompaña a una cita importante. Nunca se lo pidió directamente; esperaba que lo supiera. Cuando llega a casa se muestra distante y responde con monosílabos.',open:['¿Qué parte es necesidad y qué parte es expectativa?','¿Qué habría cambiado con una petición previa?','¿Cómo se puede pedir sin convertirlo en una exigencia?'],quiz:{q:'¿Qué petición es más concreta?',options:['“Nunca estás cuando te necesito.”','“Quiero que seas más atento.”','“¿Podrías acompañarme mañana a la cita de las 17:00? Para mí sería importante.”','“Da igual, ya iré solo.”'],correct:2,why:'Es específica, comprensible y permite que la otra persona responda.'},dialogue:[['Terapeuta','¿Qué te gustaría pedir exactamente?'],['Paciente','Que esté más pendiente.'],['Terapeuta','¿Cómo sabríamos mañana si eso ha ocurrido?'],['Paciente','Que me pregunte cómo ha ido la cita y cene conmigo.']],pause:['¿Por qué convertir necesidades globales en conductas observables ayuda?'],exercise:'Transformar 8 frases globales (“respétame”, “ayúdame más”, “sé más cariñoso”) en peticiones concretas y negociables.',materials:['Lista de frases globales'],task:'Preparar una petición concreta y realista.',slides:['Necesidad ≠ exigencia','Haz la petición observable','Caso David','Transformar frases globales','Práctica']},
  {title:'4. Críticas, desacuerdo y límites',duration:'65 min',concepts:[['Crítica útil','Se centra en una conducta concreta y su impacto.'],['Descalificación','Convierte una conducta en una etiqueta global sobre la persona.']],caseTitle:'Caso: una reunión tensa',caseText:'Durante una reunión, una compañera dice: “Tu propuesta no tiene sentido”. Elena siente vergüenza y responde: “Pues la tuya es peor”. La discusión se personaliza.',open:['¿Qué opciones existen entre callarse y contraatacar?','¿Cómo pedir que la crítica sea más concreta?'],quiz:{q:'Una respuesta posible sería:',options:['“Cállate, tú no tienes ni idea.”','“Vale, tienes razón en todo.”','“No estoy de acuerdo. Si ves un problema concreto en la propuesta, dime cuál y lo revisamos.”','Irse sin decir nada.'],correct:2,why:'Marca desacuerdo y devuelve la conversación a conductas o argumentos concretos.'},dialogue:[['Terapeuta','¿Qué fue lo que más te activó?'],['Paciente','Que pareciera que soy incompetente.'],['Terapeuta','¿Podemos responder a la frase concreta sin defender toda tu identidad?']],pause:['¿Qué cambia al separar conducta de identidad?'],exercise:'Role-play de crítica: recibir una crítica, pedir concreción, decidir qué parte se acepta y qué parte se rechaza.',materials:['Tarjetas de críticas leves/moderadas'],task:'Practicar una frase para pedir concreción ante una crítica.',slides:['Crítica ≠ identidad','Pedir concreción','Aceptar una parte','Discrepar sin atacar','Role-play']}
 ]},
 values:{name:'Valores, emoción y decisiones',sessions:[
  {title:'1. Qué me importa y cómo se nota',duration:'65 min',concepts:[['Valor','Dirección que orienta elecciones y conductas; no es una meta que se “termina”.'],['Meta','Resultado concreto que puede alcanzarse o completarse.']],caseTitle:'Dinámica de valores',caseText:'Cada persona elegirá cinco valores de una lista y después reducirá la selección a tres. No hay una respuesta correcta: el objetivo es observar qué prioriza cada uno y cómo cambia según la situación.',open:['¿Qué valor elegirías si solo pudieras conservar tres?','¿Qué conducta de esta semana demostraría ese valor?','¿Hay valores importantes que ahora mismo estés descuidando?'],values:['Familia','Amistad','Salud','Humor','Solidaridad','Autonomía','Aprendizaje','Creatividad','Honestidad','Seguridad','Aventura','Responsabilidad','Cuidado','Justicia','Trabajo','Espiritualidad','Curiosidad','Lealtad','Descanso','Contribución'],quiz:{q:'¿Cuál de estas opciones describe mejor un valor?',options:['“Perder 5 kg.”','“Ser una persona que cuida su salud.”','“Conseguir un contrato indefinido.”','“Terminar un curso.”'],correct:1,why:'Cuidar la salud es una dirección continua; las otras opciones son metas concretas.'},dialogue:[['Terapeuta','Dices que la familia es muy importante. ¿Cómo se vería ese valor esta semana?'],['Paciente','Podría llamar a mi hermano.'],['Terapeuta','Eso convierte un valor abstracto en una conducta concreta.']],pause:['¿Qué diferencia hay entre decir “la familia me importa” y actuar en esa dirección?'],guidedExercise:'Versión cerrada sin autorrevelación: presenta a Ana, que debe elegir entre acompañar a un familiar a una cita importante y cumplir un compromiso previo con un amigo. Reparte tres tarjetas —Familia, Lealtad, Responsabilidad— y pide al grupo elegir cuál parece priorizar Ana en cada una de tres decisiones ficticias. Después pregunta: “¿Puede haber dos respuestas razonables si cambian los valores priorizados?”.',exercise:'Selección 5→3 valores. Después, cada participante escribe una conducta pequeña que represente uno de ellos. Puesta en común voluntaria.',materials:['Lista de 20 valores','Papel y bolígrafo'],task:'Realizar una conducta pequeña alineada con uno de los tres valores elegidos.',slides:['Valores: direcciones, no metas','Elige 5','Ahora elige 3','¿Cómo se ve un valor en la conducta?','Compromiso pequeño']},
  {title:'2. Cuando dos valores chocan',duration:'70 min',concepts:[['Conflicto de valores','Dos direcciones importantes pueden competir; decidir implica priorizar temporalmente sin negar la importancia de la otra.']],caseTitle:'Caso: ayudar a un amigo o proteger mis límites',caseText:'Un amigo pide que canceles un plan familiar importante para ayudarle con una mudanza de última hora. Para ti son importantes la lealtad y la familia. No puedes hacer ambas cosas al mismo tiempo.',open:['¿Qué consejo le darías a un amigo en esta situación?','¿Qué te aconsejarías a ti mismo?','¿Sale el mismo consejo? ¿Por qué?','¿Qué valor estás priorizando y qué coste aceptas?'],quiz:{q:'¿Qué respuesta refleja mejor un conflicto de valores?',options:['“Si elijo una cosa significa que la otra no me importa.”','“Puedo valorar ambas cosas y aun así priorizar una hoy.”','“Siempre debo escoger a los demás antes que a mí.”','“Los valores sirven para evitar decisiones difíciles.”'],correct:1,why:'Priorizar en una situación concreta no elimina el valor de la alternativa.'},dialogue:[['Terapeuta','¿Qué le dirías a tu mejor amigo si estuviera en tu situación?'],['Paciente','Que mantenga el plan con su familia y ayude otro día.'],['Terapeuta','¿Y a ti qué te dices?'],['Paciente','Que si no voy soy mala persona.'],['Terapeuta','Ahí aparece una regla distinta para ti que para los demás.']],pause:['¿Somos más exigentes con nosotros que con un amigo?','¿Qué valor o miedo explica esa diferencia?'],exercise:'En parejas: cada persona recibe un dilema con dos valores en conflicto. Primero aconseja a “un amigo”; después responde qué haría ella misma. Comparar diferencias.',materials:['Tarjetas con 6 dilemas de valores','Lista de valores'],task:'Ante una decisión real, escribir: valores implicados, prioridad actual y coste que acepto.',slides:['Dos valores pueden chocar','Dilema: amigo vs familia','¿Qué aconsejarías a un amigo?','¿Qué te aconsejas a ti?','Elegir también implica aceptar un coste']},
  {title:'3. Emoción, pensamiento y conducta',duration:'60 min',concepts:[['Emoción','Respuesta afectiva con cambios subjetivos y corporales.'],['Pensamiento','Interpretación, imagen o evaluación que aparece ante una situación.'],['Conducta','Lo que hacemos o dejamos de hacer en respuesta a la situación.']],caseTitle:'Caso: mensaje sin respuesta',caseText:'Envías un mensaje importante y pasan seis horas sin respuesta. Piensas “está enfadado conmigo”, notas ansiedad y decides enviar cinco mensajes más.',open:['¿Qué es situación, qué es pensamiento, qué es emoción y qué es conducta?','¿Qué otras interpretaciones son posibles?','¿Qué cambia si la conducta es esperar una hora antes de actuar?'],quiz:{q:'“Seguro que no me responde porque ya no le importo” es principalmente:',options:['Una emoción','Un pensamiento/interpretación','Una conducta','Un hecho objetivo'],correct:1,why:'Es una interpretación sobre la situación, no un hecho comprobado.'},dialogue:[['Terapeuta','¿Qué sabes con certeza?'],['Paciente','Solo que no ha respondido.'],['Terapeuta','¿Y qué has añadido tú?'],['Paciente','Que está enfadado y que no le importo.']],pause:['¿Cómo cambia la emoción cuando distinguimos dato de interpretación?'],exercise:'Clasificar tarjetas en situación / pensamiento / emoción / conducta y después construir cadenas alternativas.',materials:['Tarjetas de ejemplos'],task:'Registrar una cadena breve situación–pensamiento–emoción–conducta.',slides:['Cuatro piezas','Situación','Pensamiento','Emoción','Conducta','Cambiar un eslabón']}
 ]},
 psychosis:{name:'Metacognición y psicosis',sessions:[
  {title:'1. Hechos, interpretaciones y certeza',duration:'65 min',concepts:[['Hecho','Información directamente observable o verificable.'],['Interpretación','Explicación que construimos a partir de los datos disponibles.'],['Certeza','Grado de seguridad que damos a una interpretación.']],caseTitle:'Caso: no me saludó',caseText:'Al entrar en una cafetería, una persona conocida mira hacia otro lado y no saluda. La primera interpretación es: “me evita porque habla mal de mí”.',open:['¿Qué sabemos con certeza?','¿Qué explicaciones alternativas existen?','¿Qué dato necesitaríamos para aumentar o reducir la certeza?'],quiz:{q:'¿Cuál es un hecho?',options:['“Me desprecia.”','“Me vio y fingió no verme.”','“Miró hacia otro lado y no me saludó.”','“Seguro que alguien le ha hablado de mí.”'],correct:2,why:'Describe lo observable sin añadir una explicación.'},dialogue:[['Terapeuta','¿Qué porcentaje de seguridad das a tu primera explicación?'],['Paciente','Un 90%.'],['Terapeuta','Vamos a buscar tres alternativas antes de volver a estimar la certeza.'],['Paciente','Podría no haberme visto, estar preocupado o ir con prisa.']],pause:['¿Cambiar la certeza significa negar la experiencia?','¿Qué utilidad tiene dejar un margen de duda?'],exercise:'Tarjetas ambiguas: separar datos e interpretaciones; generar al menos tres explicaciones y puntuar certeza 0–100 antes y después.',materials:['Tarjetas con situaciones ambiguas','Escala 0–100'],task:'Ante una situación ambigua, anotar un hecho y dos interpretaciones alternativas.',slides:['Nuestro cerebro interpreta','Hecho vs interpretación','Caso: no me saludó','Tres explicaciones','¿Cuánta certeza?']},
  {title:'2. Saltar a conclusiones',duration:'60 min',concepts:[['Decisión rápida','Conclusión tomada con pocos datos; puede ser útil a veces, pero aumenta errores en situaciones ambiguas.']],caseTitle:'Caso: el correo del jefe',caseText:'Recibes un correo que dice solo: “Mañana necesito hablar contigo”. Piensas inmediatamente que te van a despedir.',open:['¿Qué datos faltan?','¿Qué otras explicaciones caben?','¿Qué haría una persona que decide esperar a tener más información?'],quiz:{q:'¿Qué estrategia reduce el salto a conclusiones?',options:['Buscar solo información que confirme la primera idea.','Tomar una decisión inmediata para reducir la incertidumbre.','Recoger más datos y generar alternativas antes de concluir.','Evitar pensar en el tema por completo.'],correct:2,why:'Añadir información y alternativas reduce el riesgo de convertir una hipótesis en certeza.'},dialogue:[['Terapeuta','¿Qué evidencia tienes de que sea un despido?'],['Paciente','Ninguna directa.'],['Terapeuta','¿Qué datos te faltan antes de concluir?']],pause:['¿Por qué la incertidumbre empuja a cerrar una explicación demasiado pronto?'],exercise:'Juego de pistas progresivas: el grupo recibe una situación con 1, 2 y 4 datos; tras cada ronda registra su hipótesis y nivel de certeza.',materials:['Tarjetas de pistas'],task:'Esperar a disponer de un dato adicional antes de cerrar una conclusión en una situación cotidiana ambigua.',slides:['Pocos datos, mucha certeza','El correo de mañana','¿Qué información falta?','Hipótesis ≠ hecho','Esperar un dato más']}
 ]},
 anxiety:{name:'Ansiedad, pánico y regulación',sessions:[
  {title:'1. El ciclo de la ansiedad',duration:'60 min',concepts:[['Alarma','Activación fisiológica que prepara al organismo para responder.'],['Interpretación catastrófica','Lectura amenazante de sensaciones o situaciones que puede amplificar la alarma.'],['Evitación','Reducir contacto con lo temido; alivia a corto plazo pero puede mantener el miedo.']],caseTitle:'Caso: centro comercial',caseText:'Ana nota palpitaciones en un centro comercial. Piensa “me voy a desmayar”, sale rápidamente y se siente mejor. La semana siguiente decide no volver.',open:['¿Qué parte del ciclo produce alivio inmediato?','¿Qué aprende el cerebro al salir siempre?','¿Qué alternativa gradual podría plantearse?'],quiz:{q:'¿Qué conducta puede mantener el miedo a largo plazo?',options:['Permanecer gradualmente en la situación el tiempo acordado.','Salir siempre en cuanto aparece ansiedad.','Observar cómo sube y baja la activación.','Revisar interpretaciones catastróficas.'],correct:1,why:'La evitación inmediata reduce ansiedad a corto plazo y puede reforzar la idea de que la situación era peligrosa.'},dialogue:[['Terapeuta','¿Qué pasó después de salir?'],['Paciente','La ansiedad bajó.'],['Terapeuta','¿Y qué aprendiste de esa bajada?'],['Paciente','Que salir me salva.'],['Terapeuta','Ese aprendizaje es justo lo que tendremos que revisar de forma gradual y segura.']],pause:['¿Por qué algo que ayuda a corto plazo puede perjudicar a largo plazo?'],exercise:'Construir un círculo situación–pensamiento–sensación–conducta–consecuencia con un caso ficticio y proponer un punto de intervención.',materials:['Pizarra o diapositiva del ciclo'],task:'Identificar un episodio y completar el ciclo sin intentar cambiarlo todavía.',slides:['Ansiedad = alarma','El círculo que se retroalimenta','Caso: centro comercial','Alivio corto vs aprendizaje largo','¿Dónde podemos intervenir?']},
  {title:'2. Relajación muscular progresiva',duration:'55 min',concepts:[['Tensión–distensión','Contrastar de forma deliberada tensión suave y relajación para reconocer y reducir tensión muscular.']],caseTitle:'Antes de empezar',caseText:'La práctica se realiza sentados, sin dolor y sin forzar. Si un grupo muscular molesta, se omite. El objetivo no es “hacer desaparecer” toda ansiedad, sino aprender a detectar y soltar tensión.',open:['¿Dónde notas primero la tensión cuando estás activado?','¿Qué diferencia hay entre relajarse y obligarse a no sentir ansiedad?'],quiz:{q:'Durante la práctica conviene:',options:['Tensar al máximo aunque duela.','Mantener la respiración.','Tensar suavemente y soltar, observando el contraste.','Hacerla solo cuando la ansiedad es extrema.'],correct:2,why:'La práctica busca conciencia y distensión, no esfuerzo intenso.'},dialogue:[['Terapeuta','No buscamos ganar una competición de relajación.'],['Paciente','Entonces, ¿si sigo algo nervioso lo estoy haciendo mal?'],['Terapeuta','No. El objetivo es notar y soltar tensión, no controlar cada sensación.']],pause:['¿Qué expectativa poco realista puede convertir una técnica de relajación en otra fuente de presión?'],exercise:'Práctica guiada breve: manos/brazos, hombros, cara, abdomen y piernas. Tensión suave 5 segundos y distensión 15–20 segundos.',materials:['Sillas cómodas','Audio/lectura guiada opcional'],task:'Practicar 10 minutos en un momento tranquilo 3–4 días y observar qué grupos acumulan más tensión.',audio:'Siéntate con apoyo y deja los pies en el suelo. Observa primero cómo está tu cuerpo sin intentar cambiarlo. Cierra suavemente los puños durante cinco segundos, sin hacerte daño. Ahora suelta y nota durante unos segundos la diferencia entre tensión y distensión. Lleva después los hombros ligeramente hacia arriba, mantén unos segundos y suelta. Frunce suavemente la frente y relaja. Contrae de forma ligera el abdomen y suelta. Finalmente, presiona los pies contra el suelo unos segundos y deja de hacerlo. Respira con normalidad. No hace falta conseguir una relajación perfecta. Solo observa dónde puedes aflojar un poco más.',slides:['Relajación muscular progresiva','No buscamos “cero ansiedad”','Tensión suave · 5 s','Soltar · 15–20 s','Observar el contraste','Práctica guiada']}
 ]},
 motivation:{name:'Motivación y prevención de recaídas',sessions:[
  {title:'1. Ambivalencia y razones propias',duration:'60 min',concepts:[['Ambivalencia','Tener a la vez razones para mantener una conducta y razones para cambiarla.'],['Lenguaje de cambio','Expresiones propias sobre deseo, capacidad, razones, necesidad o compromiso para cambiar.']],caseTitle:'Caso: “Me ayuda y me perjudica”',caseText:'Óscar dice que el cannabis le ayuda a desconectar por la noche, pero también reconoce que al día siguiente se levanta tarde, falta a actividades y discute más con su familia.',open:['¿Qué gana a corto plazo?','¿Qué costes aparecen a medio plazo?','¿Qué razones para cambiar son de Óscar y cuáles serían de otras personas?'],quiz:{q:'¿Cuál es una respuesta más compatible con entrevista motivacional?',options:['“Tienes que dejarlo ya.”','“Si sigues así vas a fracasar.”','“Por una parte te ayuda a desconectar y por otra está interfiriendo con cosas que te importan. ¿Qué te preocupa más de todo esto?”','“No hablemos de lo bueno, centrémonos solo en los riesgos.”'],correct:2,why:'Refleja la ambivalencia y evoca la perspectiva de la persona sin confrontación.'},dialogue:[['Terapeuta','¿Qué te gusta de consumir?'],['Paciente','Me baja las vueltas.'],['Terapeuta','¿Y qué parte te está empezando a cansar?'],['Paciente','Perder las mañanas y discutir.']],pause:['¿Por qué preguntar también por las ventajas puede facilitar una conversación más honesta?'],exercise:'Balanza decisional con un hábito ficticio: ventajas/costes de mantener y cambiar; después identificar una razón propia para avanzar.',materials:['Plantilla de cuatro cuadrantes'],task:'Elegir un cambio pequeño y puntuar importancia/confianza de 0 a 10.',slides:['Ambivalencia es normal','Lo que ayuda / lo que cuesta','Razones propias','Escala 0–10','Un paso pequeño']}
 ]}
};

function fillCycles(){const cycle=$('#groupCycle');cycle.innerHTML=Object.entries(groupCycles).map(([k,v])=>`<option value="${k}">${esc(v.name)}</option>`).join('');fillSessions()}
function fillSessions(){const c=groupCycles[$('#groupCycle').value];$('#groupSession').innerHTML=c.sessions.map((s,i)=>`<option value="${i}">${esc(s.title)}</option>`).join('')}
function adaptGroup(feedback){const n=norm(feedback), tips=[];if(/poco dinam|poca particip|silencio|pasiv/.test(n))tips.push('Mantener formato cerrado: votación, elección A/B/C/D y ensayo con frases ya preparadas; no pedir experiencias personales.');if(/monopol|interrump|hablan mucho|desbord/.test(n))tips.push('Usar turnos breves y limitar intervenciones a aproximadamente un minuto.');if(/dificultad.*compr|atencion|cognitiv/.test(n))tips.push('Reducir explicación verbal y aumentar ejemplos, tarjetas y repetición.');if(/conflict|tension/.test(n))tips.push('Trabajar sobre personajes ficticios y evitar interpretar a miembros del grupo.');return tips}
function guidedScriptHtml(s){return `<div class="guidedScript"><b>Guion cerrado de conducción</b><div class="guidedStep exactPhrase">“Hoy vamos a trabajar con un caso ficticio. No hace falta contar nada personal. Primero escuchamos, después elegimos entre varias opciones y al final practicamos una respuesta concreta.”</div><div class="guidedStep"><b>1.</b> Lee el caso completo sin interrumpirlo y pide solo una votación rápida: “¿Qué opción encaja mejor: A, B, C o D?”</div><div class="guidedStep"><b>2.</b> Lee las cuatro respuestas de la pregunta de elección. Pide levantar uno, dos, tres o cuatro dedos. No solicites justificación todavía.</div><div class="guidedStep"><b>3.</b> Da la explicación preparada: ${esc(s.quiz?.why||'Revisar juntos por qué una opción encaja mejor que las demás.')}</div><div class="guidedStep"><b>4.</b> Haz el diálogo terapeuta–paciente exactamente como está escrito, repartiendo los dos papeles entre terapeuta y un voluntario o leyéndolo tú mismo.</div><div class="guidedStep"><b>5.</b> Ejecuta la dinámica concreta con instrucciones breves y tiempo limitado. Si nadie quiere participar, usa dos personajes ficticios y pide al grupo que elija cuál de dos respuestas sería más útil.</div><div class="guidedStep exactPhrase">Cierre: “No buscamos contar intimidades. La idea de hoy es llevarnos una herramienta y reconocer cuándo podría ser útil.”</div></div>`}
function renderGroupSession(){const cycle=groupCycles[$('#groupCycle').value], idx=Number($('#groupSession').value)||0, s=cycle.sessions[idx];currentGroupSession=s;const adapt=adaptGroup($('#groupFeedback').value);const guided=$('#groupGuidance').value==='guided';presentationSlides=s.slides||[s.title,...s.open];slideIndex=0;
 const concepts=(s.concepts||[]).map(([a,b])=>`<div class="concept"><b>${esc(a)}</b><div class="small">${esc(b)}</div></div>`).join('');
 const dialogue=(s.dialogue||[]).map(([who,t])=>`<div class="turn"><span class="${who==='Terapeuta'?'therapist':'patient'}">${esc(who)}:</span> ${esc(t)}</div>`).join('');
 const values=s.values?`<div class="values">${s.values.map(v=>`<span class="valueChip">${esc(v)}</span>`).join('')}</div>`:'';
 $('#groupOutput').innerHTML=`<div class="groupSession"><div class="groupHero"><div class="eyebrow">${esc(cycle.name)}</div><h2>${esc(s.title)}</h2><div class="small">Duración orientativa: ${esc(s.duration||'60 min')}</div></div><div class="groupBody">
 ${guided?guidedScriptHtml(s):''}<h3>1 · Conceptos para abrir la sesión</h3><div class="conceptGrid">${concepts}</div>${values}
 <h3>2 · Relato / caso para trabajar</h3><div class="case"><b>${esc(s.caseTitle)}</b><br>${esc(s.caseText)}</div>${guided?`<details><summary>Preguntas abiertas opcionales</summary><div class="detailBody"><ul class="questions">${(s.open||[]).map(q=>`<li>${esc(q)}</li>`).join('')}</ul></div></details>`:`<ul class="questions">${(s.open||[]).map(q=>`<li>${esc(q)}</li>`).join('')}</ul>`}
 <h3>3 · Pregunta de elección al grupo</h3><div><b>${esc(s.quiz.q)}</b></div><div class="mcq">${s.quiz.options.map((o,i)=>`<button type="button" data-q="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><div id="quizFeedback" class="feedback">Pulsa una opción para mostrar la explicación.</div>
 <h3>4 · Diálogo terapeuta–paciente</h3><div class="dialogue">${dialogue}</div>${(s.pause||[]).map(q=>`<div class="pause">⏸️ <b>Pausa al grupo:</b> ${esc(q)}</div>`).join('')}
 <h3>5 · Dinámica concreta</h3><div class="case">${esc(guided&&s.guidedExercise?s.guidedExercise:s.exercise)}</div><b>Material</b><ul class="materials">${(s.materials||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>
 ${adapt.length?`<h3>Adaptación al grupo</h3><ul class="questions">${adapt.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}
 <h3>6 · Cierre / tarea</h3><div class="suggestionBox">${esc(s.task)}</div>
 <div class="actions"><button id="presentGroup">📺 Modo pantalla</button>${s.audio?'<button id="speakGroup" class="secondary">▶️ Leer práctica</button>':''}<button id="saveGroup" class="ghost">Guardar sesión</button></div>
 </div></div>`;
 $$('.mcq button').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.q);$$('.mcq button').forEach(x=>x.classList.remove('correct','wrong'));b.classList.add(i===s.quiz.correct?'correct':'wrong');$('#quizFeedback').textContent=s.quiz.why}));
 $('#presentGroup').addEventListener('click',openPresentation);$('#saveGroup').addEventListener('click',saveGroupHistory);if(s.audio)$('#speakGroup').addEventListener('click',()=>speak(s.audio));
}
function groupHistory(){try{return JSON.parse(localStorage.getItem('psikiaGroupHistoryV2')||'[]')}catch{return []}}
function saveGroupHistory(){if(!currentGroupSession)return;const h=groupHistory();h.unshift({date:new Date().toISOString(),cycle:groupCycles[$('#groupCycle').value].name,session:currentGroupSession.title,feedback:$('#groupFeedback').value.trim().slice(0,600)});localStorage.setItem('psikiaGroupHistoryV2',JSON.stringify(h.slice(0,50)));renderGroupHistory();alert('Sesión guardada en el histórico local del grupo.')}
function renderGroupHistory(){const h=groupHistory();$('#groupHistory').innerHTML=h.length?h.map(x=>`<div class="historyItem"><div class="meta">${new Date(x.date).toLocaleDateString('es-ES')} · ${esc(x.cycle)}</div><b>${esc(x.session)}</b>${x.feedback?`<div>${esc(x.feedback)}</div>`:''}</div>`).join(''):'Sin sesiones guardadas.'}
function openPresentation(){if(!presentationSlides.length)return;$('#presentation').classList.add('active');$('#presentation').setAttribute('aria-hidden','false');renderSlide();if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>{})}
function closePresentation(){ $('#presentation').classList.remove('active');$('#presentation').setAttribute('aria-hidden','true');if(document.fullscreenElement)document.exitFullscreen().catch(()=>{}) }
function renderSlide(){const raw=presentationSlides[slideIndex]||'';$('#slide').innerHTML=`<div class="eyebrow">Psikia Hub · Grupo</div><h1>${esc(raw)}</h1><p>${slideIndex===0?esc(currentGroupSession?.caseText||''):'Pregunta abierta: ¿qué ideas, ejemplos o dudas os surgen?'}</p><div class="small">${slideIndex+1} / ${presentationSlides.length}</div>`}
function speak(text){if(!('speechSynthesis' in window))return alert('Este dispositivo no permite lectura de texto desde la app.');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';u.rate=.9;speechSynthesis.speak(u)}

// ---- EVENTS ----
$$('nav button').forEach(b=>b.addEventListener('click',()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(t=>t.classList.remove('active'));$(`#tab-${b.dataset.tab}`).classList.add('active')}));
$('#patientCode').addEventListener('input',()=>{updateContextHint();scheduleDraftSave()});$('#visitType').addEventListener('change',scheduleDraftSave);$('#raw').addEventListener('input',scheduleDraftSave);$('#groupCycle').addEventListener('change',fillSessions);$('#groupGuidance').addEventListener('change',()=>{if(currentGroupSession)renderGroupSession()});
$('#generate').addEventListener('click',()=>{if(dictationWanted)stopDictation('Dictado detenido para generar la nota. Todo el texto está guardado.');const text=$('#raw').value.trim();if(!text)return alert('Dicta o escribe primero la consulta.');lastInput=text;currentType=$('#visitType').value;saveDraftNow();fullReport=buildReport(text,currentType);compactMode=shouldCompact(text,currentType);currentReport=compactMode?compactReport(fullReport,currentType):{...fullReport};renderReport();$('#saveHint').textContent=getCode()?'Revisa la nota y guarda la evolución o envíala para actualizar el contexto local.':''});
$('#clear').addEventListener('click',()=>{if(dictationWanted)stopDictation();$('#raw').value='';$('#resultCard').hidden=true;currentReport={};fullReport={};lastInput='';$('#saveHint').textContent='';clearDraft()});
$('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(reportText());alert('Informe copiado.')}catch{alert('No se pudo copiar automáticamente. Mantén pulsado sobre el texto para copiarlo.')}});
$('#saveContext').addEventListener('click',saveCurrentContext);
$('#email').addEventListener('click',()=>{const to=$('#emailAddress').value.trim();if(!to)return alert('Configura el correo profesional en Ajustes.');if(getCode())saveCurrentContext();const subject=encodeURIComponent(`Psikia Hub · ${labels[currentType]}${getCode()?` · ${getCode()}`:''}`);const body=encodeURIComponent(reportText());location.href=`mailto:${encodeURIComponent(to)}?subject=${subject}&body=${body}`});
$('#dictate').addEventListener('click',toggleDictation);$('#addDiagnostic').addEventListener('click',addDiagnosticToDocument);$('#addTherapy').addEventListener('click',addTherapyToDocument);
$('#prepareGroup').addEventListener('click',renderGroupSession);$('#clearGroupHistory').addEventListener('click',()=>{if(confirm('¿Borrar el histórico grupal local?')){localStorage.removeItem('psikiaGroupHistoryV2');renderGroupHistory()}});
$('#clearPatients').addEventListener('click',()=>{if(confirm('¿Borrar todos los contextos locales A/AB?')){localStorage.removeItem('psikiaPatientsV2');updateContextHint();alert('Contextos locales borrados.')}});
$('#prevSlide').addEventListener('click',()=>{slideIndex=(slideIndex-1+presentationSlides.length)%presentationSlides.length;renderSlide()});$('#nextSlide').addEventListener('click',()=>{slideIndex=(slideIndex+1)%presentationSlides.length;renderSlide()});$('#closePresentation').addEventListener('click',closePresentation);

document.addEventListener('visibilitychange',()=>{saveDraftNow();if(document.visibilityState==='visible'&&dictationWanted&&!recognition){acquireWakeLock();startRecognitionLoop()}});
window.addEventListener('pagehide',()=>saveDraftNow());
restoreDraft();fillCycles();renderGroupHistory();updateContextHint();if(!$('#raw').value)setDictationStatus('Guardado automático activo. Durante el dictado intentaremos mantener la pantalla encendida.');
