'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentReport={}, currentSections=[], lastSourceText='';

const templates={
 initial:{label:'Valoración inicial / ingreso',sections:['Motivo de consulta / derivación','Antecedentes médicos no psiquiátricos','Antecedentes psiquiátricos personales','Antecedentes familiares psiquiátricos','Consumo de sustancias','Situación sociolaboral y funcional','Tratamiento farmacológico actual','Enfermedad actual / evolución longitudinal','Exploración psicopatológica','Pruebas complementarias','Juicio clínico / diagnóstico','Plan de tratamiento e intervención','Disposición / seguimiento']},
 evolution:{label:'Evolutivo / seguimiento',sections:['Resumen clínico longitudinal','Evolución / enfermedad actual','Exploración psicopatológica comparativa','Juicio clínico','Plan de tratamiento','Seguimiento / próxima cita']},
 pti:{label:'Plan de Tratamiento Individualizado (PTI)',sections:['Resumen clínico y funcional','Necesidades / problemas activos','Objetivos del ingreso','Intervención de Psiquiatría','Intervención de Psicología','Intervención de Enfermería','Intervención de Terapia Ocupacional','Intervención de Trabajo Social','Otras intervenciones / coordinación','Indicadores de seguimiento y revisión del PTI']},
 discharge:{label:'Informe de alta',sections:['Motivo y contexto del ingreso','Antecedentes relevantes','Evolución durante el ingreso','Intervenciones realizadas','Exploración psicopatológica al alta','Pruebas complementarias relevantes','Diagnóstico al alta','Tratamiento al alta','Situación funcional al alta','Plan de seguimiento y recursos','Objetivos pendientes / recomendaciones']},
 emergency:{label:'Urgencias / valoración única',sections:['Motivo de consulta','Antecedentes relevantes','Situación precipitante / enfermedad actual','Exploración psicopatológica','Valoración de riesgo','Pruebas / actuaciones realizadas','Juicio clínico','Tratamiento / intervención','Disposición y plan inmediato']}
};

const privacyPatterns=[
 ['DNI/NIE',/\b(?:\d{8}[A-Z]|[XYZ]\d{7}[A-Z])\b/ig],['email',/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/ig],['teléfono',/(?:\+34\s*)?(?:[6789]\d{2})(?:[ .-]?\d{3}){2}/g],['nº historia',/\b(?:nhc|n[úu]m(?:ero)?\s*de\s*historia|historia\s*cl[ií]nica)\s*[:#-]?\s*[A-Z0-9-]{4,}\b/ig],['dirección',/\b(?:calle|c\/|avenida|avda\.?|plaza|paseo|carretera)\s+[\p{L}0-9 .ºª-]{3,}/igu],['código postal',/\b\d{5}\b/g]
];
function privacyScan(text){const hits=[];privacyPatterns.forEach(([n,re])=>{re.lastIndex=0;if(re.test(text))hits.push(n)});return [...new Set(hits)]}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function normalize(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function sentences(text){return String(text||'').replace(/\r/g,'\n').split(/\n+|(?<=[.!?;])\s+/).map(x=>x.trim()).filter(Boolean)}

const cueMap={
 'Motivo de consulta / derivación':['motivo','derivad','primera cita','consulta por','ingreso por','remitid'],
 'Antecedentes médicos no psiquiátricos':['antecedentes medicos','antecedentes médicos','quirurg','somatic','alerg','diabetes','hipertension','hipertensión','cardiop','renal','hepatic'],
 'Antecedentes psiquiátricos personales':['antecedentes psiqui','episodios previos','ingresos previos','salud mental previo','diagnosticado previamente','tratamientos previos'],
 'Antecedentes familiares psiquiátricos':['antecedentes familiares','hermana','hermano','madre','padre','familiares psiqui'],
 'Consumo de sustancias':['consumo','cannabis','alcohol','cocaina','cocaína','opiace','tabaco','toxic','abstinencia','porros'],
 'Situación sociolaboral y funcional':['trabaja','paro','desemple','casad','hijos','pareja','convive','funcional','autocuidado','ocupacional','actividad','aislamiento','socializa','cuadrilla','laboral'],
 'Tratamiento farmacológico actual':['tratamiento actual','tratamiento farmac','toma ','mg','miligr','escitalopram','fluoxetina','mirtazapina','lorazepam','antipsicot','antidepres','pauta'],
 'Enfermedad actual / evolución longitudinal':['enfermedad actual','desde hace','a raiz','a raíz','progresivamente','ultimos','últimos','meses','semanas','inicio','empeora','crisis','desencaden','actualmente'],
 'Exploración psicopatológica':['exploracion','exploración','consciente','orientad','contacto visual','discurso','hipotimia','eutimia','ansiedad','delir','alucin','ideacion','ideación','planes de futuro','sueño','apetito','abulia','anhedonia','psicomot'],
 'Pruebas complementarias':['analit','ecg','electrocard','tac','resonancia','rm ','orina','toxicologia','toxicología','niveles','mccb','escala'],
 'Juicio clínico / diagnóstico':['juicio clinico','juicio clínico','diagnost','impresion clinica','impresión clínica','compatible con'],
 'Plan de tratamiento e intervención':['plan de tratamiento','plan de intervencion','plan de intervención','indicamos','recomendamos','mantener','retirar','iniciar','cita','enfermeria','enfermería','psicologia','psicología','terapia ocupacional','trabajo social','rehabilit'],
 'Disposición / seguimiento':['ingreso para','cita dentro','revision en','revisión en','seguimiento','alta a','derivacion','derivación'],
 'Valoración de riesgo':['riesgo','autolit','suicid','heteroagres','autoagres','planificad','intento','acceso a medios'],
 'Pruebas / actuaciones realizadas':['pruebas','analit','ecg','contencion','contención','medicacion administrada','medicación administrada','observacion','observación'],
 'Tratamiento / intervención':['tratamiento','intervencion','intervención','administramos','pautamos','psicoeduc'],
 'Disposición y plan inmediato':['alta','ingreso','observacion','observación','deriv','seguimiento','acompañad','cita'],
 'Evolución / enfermedad actual':['evolucion','evolución','desde la ultima','desde la última','desde las ultimas','desde las últimas','ha mejorado','ha empeorado','progresos','persiste','persisten','respuesta','tolerado','funcional'],
 'Exploración psicopatológica comparativa':['exploracion','exploración','consciente','orientad','discurso','crisis','agoraf','afectiv','planes de futuro','sueño','apetito','delir','alucin','ideacion','ideación'],
 'Juicio clínico':['juicio clinico','juicio clínico','diagnost','se mantiene','impresion','impresión'],
 'Plan de tratamiento':['plan','mantener','retirar','eliminamos','iniciar','tratamiento','pauta','psicolog','enfermer','medidas','intervencion','intervención'],
 'Seguimiento / próxima cita':['cita','revision','revisión','seguimiento','dentro de','en tres meses','en dos meses','semanas'],
 'Motivo y contexto del ingreso':['motivo','ingreso','deriv','contexto del ingreso'],
 'Antecedentes relevantes':['antecedent','historia previa','consumo previo','tratamientos previos'],
 'Evolución durante el ingreso':['evolucion','evolución','durante el ingreso','mejoria','mejoría','progresivamente','respuesta'],
 'Intervenciones realizadas':['intervenciones','psicoterapia','grupo','terapia ocupacional','enfermeria','enfermería','trabajo social','rehabilitacion','rehabilitación'],
 'Exploración psicopatológica al alta':['exploracion','exploración','al alta','consciente','orientad','discurso','afecto','ideacion','ideación','delir','alucin'],
 'Pruebas complementarias relevantes':['analit','ecg','electrocard','tac','resonancia','niveles','pruebas'],
 'Diagnóstico al alta':['diagnostico','diagnóstico','juicio clinico','juicio clínico'],
 'Tratamiento al alta':['tratamiento al alta','pauta al alta','mg','mantener','medicacion','medicación'],
 'Situación funcional al alta':['funcional','autocuidado','social','ocupacional','laboral','avd','autonomia','autonomía'],
 'Plan de seguimiento y recursos':['seguimiento','cita','deriv','recurso','csm','tercer sector','anasaps'],
 'Objetivos pendientes / recomendaciones':['pendiente','objetivo','recomend','continuar','mantener trabajo']
};
function scoreFor(sec,s){const n=normalize(s);return (cueMap[sec]||[]).reduce((a,k)=>a+(n.includes(normalize(k))?1:0),0)}
function uniqueJoin(arr){const seen=new Set(), out=[];arr.forEach(x=>{const k=normalize(x).replace(/[^a-z0-9]+/g,' ').trim();if(k&&!seen.has(k)){seen.add(k);out.push(x)}});return out.join(' ')}
function classifyInitial(text,sections){const out=Object.fromEntries(sections.map(s=>[s,[]]));sentences(text).forEach(sent=>{let best=sections.includes('Enfermedad actual / evolución longitudinal')?'Enfermedad actual / evolución longitudinal':sections[0], max=0;sections.forEach(sec=>{const sc=scoreFor(sec,sent);if(sc>max){max=sc;best=sec}});out[best].push(sent)});return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,uniqueJoin(v)]))}
function extractTreatment(text){return sentences(text).filter(x=>/\b(?:mg|miligr|tratamiento|toma|pauta|escitalopram|fluoxetina|mirtazapina|lorazepam|sertralina|venlafaxina|duloxetina|vortioxetina|aripiprazol|olanzapina|risperidona|paliperidona|quetiapina|clozapina|litio|valproato|lamotrigina)\b/i.test(x)).slice(0,5).join(' ')}
function getContext(){try{return JSON.parse(localStorage.getItem('psikiaContext')||'null')}catch{return null}}
function contextText(){const c=getContext();return c?.summary||''}
function contextHeader(){const c=getContext();if(!c)return 'No consta contexto longitudinal previo guardado.';return c.summary}
function buildEvolution(text){const base=classifyInitial(text,['Evolución / enfermedad actual','Exploración psicopatológica comparativa','Juicio clínico','Plan de tratamiento','Seguimiento / próxima cita']);const out={};out['Resumen clínico longitudinal']=contextHeader();out['Evolución / enfermedad actual']=base['Evolución / enfermedad actual']||text;out['Exploración psicopatológica comparativa']=base['Exploración psicopatológica comparativa']||sentences(text).filter(x=>/consciente|orientad|discurso|crisis|agoraf|afect|futuro|duerme|come|sueño|apetito|delir|alucin|ideacion|ideación/i.test(x)).join(' ');out['Juicio clínico']=sentences(text).filter(x=>/juicio|diagnost|se mantiene|compatible/i.test(x)).join(' ')||'Se mantiene juicio clínico previo, salvo revisión facultativa.';out['Plan de tratamiento']=sentences(text).filter(x=>/mantener|retirar|iniciar|pauta|tratamiento|psicolog|enfermer|medidas|intervencion/i.test(x)).join(' ');out['Seguimiento / próxima cita']=sentences(text).filter(x=>/cita|revision|revisión|seguimiento|meses|semanas/i.test(x)).slice(-3).join(' ');return out}
function buildPTI(text){const c=contextHeader();const n=normalize(`${c} ${text}`);const goals=[];if(/depres|hipotim|anhed|apat|abul/.test(n))goals.push('Mejorar sintomatología afectiva y recuperar actividad gratificante.');if(/autocuidado|higiene|avd/.test(n))goals.push('Mejorar autonomía y regularidad en autocuidado y actividades de la vida diaria.');if(/aisla|social|cuadrilla|interaccion|interacción/.test(n))goals.push('Incrementar participación social y reducir aislamiento.');if(/ocupacional|trabaj|empleo|actividad/.test(n))goals.push('Recuperar estructura ocupacional y avanzar hacia objetivos laborales realistas.');if(/psicos|delir|alucin/.test(n))goals.push('Reducir malestar asociado a síntomas psicóticos y mejorar estrategias de afrontamiento.');if(/consumo|cannabis|alcohol|cocaina|cocaína/.test(n))goals.push('Mantener/reducir consumo y reforzar prevención de recaídas.');if(/autolit|suicid|autoagres/.test(n))goals.push('Monitorizar riesgo y consolidar plan de seguridad y estrategias de afrontamiento.');if(!goals.length)goals.push('Mejorar funcionamiento global y avanzar en los objetivos individualizados acordados durante el ingreso.');return {
 'Resumen clínico y funcional':c,
 'Necesidades / problemas activos':text||'Completar a partir de la evolución del primer mes.',
 'Objetivos del ingreso':goals.map((g,i)=>`${i+1}. ${g}`).join('\n'),
 'Intervención de Psiquiatría':'Revisión diagnóstica longitudinal, optimización y monitorización del tratamiento psicofarmacológico, coordinación del plan y reevaluación de riesgo cuando proceda.',
 'Intervención de Psicología':'Formulación compartida, intervención cognitivo-conductual/rehabilitadora adaptada a problemas activos, entrenamiento de estrategias y prevención de recaídas.',
 'Intervención de Enfermería':'Seguimiento clínico y de adherencia, educación sanitaria, apoyo en hábitos, manejo de ansiedad/estrés y objetivos de autocuidado según necesidades.',
 'Intervención de Terapia Ocupacional':'Valoración de desempeño, estructuración de rutinas, activación ocupacional, ocio significativo y progresión de objetivos comunitarios.',
 'Intervención de Trabajo Social':'Valoración sociofamiliar, prestaciones y apoyos, recursos comunitarios/tercer sector, coordinación con red y objetivos de integración.',
 'Otras intervenciones / coordinación':'Valorar intervención familiar, recursos comunitarios y coordinación con dispositivos de referencia según evolución.',
 'Indicadores de seguimiento y revisión del PTI':'Revisar consecución de objetivos, participación en programa, autonomía, funcionamiento social/ocupacional, síntomas, adherencia y riesgo.'
}}
function buildDischarge(text){const c=contextHeader();const base=classifyInitial(text,templates.discharge.sections);base['Motivo y contexto del ingreso']=base['Motivo y contexto del ingreso']||c;base['Antecedentes relevantes']=base['Antecedentes relevantes']||c;return base}
function buildEmergency(text){return classifyInitial(text,templates.emergency.sections)}
function buildReport(text,type){if(type==='evolution')return buildEvolution(text);if(type==='pti')return buildPTI(text);if(type==='discharge')return buildDischarge(text);if(type==='emergency')return buildEmergency(text);return classifyInitial(text,templates.initial.sections)}

function renderReport(){const box=$('#reportSections');box.innerHTML='';currentSections.forEach(sec=>{const d=document.createElement('div');d.className='sectionbox';d.innerHTML=`<div class="sectiontitle">${escapeHtml(sec)}</div><div class="sectiontext" contenteditable="true" data-sec="${escapeHtml(sec)}">${escapeHtml(currentReport[sec]||'')}</div>`;box.appendChild(d)});$$('[data-sec]').forEach(el=>el.addEventListener('input',()=>{currentReport[el.dataset.sec]=el.innerText.trim()}))}
function reportText(){return currentSections.map(s=>`${s.toUpperCase()}\n${currentReport[s]||'—'}`).join('\n\n')}
function showTab(name){$$('section.tab').forEach(x=>x.classList.remove('active'));$$('nav button').forEach(x=>x.classList.remove('active'));$('#tab-'+name).classList.add('active');$(`nav button[data-tab="${name}"]`).classList.add('active')}
$$('nav button').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));

function updatePrivacy(){const text=$('#raw').value,h=privacyScan(text),el=$('#privacyResult');if(!text.trim()){el.innerHTML='';return}el.innerHTML=h.length?`<div class="notice danger">⚠️ Posibles identificadores: <b>${escapeHtml(h.join(', '))}</b>. Revisa el dictado.</div>`:'<div class="notice ok">✓ No se detectan identificadores directos obvios. Esto no garantiza anonimización completa.</div>'}
$('#raw').addEventListener('input',updatePrivacy);

const diagnosisMap=[
 {terms:['trastorno depresivo recurrente','depresion recurrente','depresión recurrente'],code:'F33.9',label:'Trastorno depresivo mayor recurrente, no especificado'},
 {terms:['episodio actual moderado','episodio depresivo moderado'],code:'F33.1',label:'Trastorno depresivo mayor recurrente, episodio actual moderado'},
 {terms:['agorafobia con trastorno de panico','agorafobia con trastorno de pánico','panico con agorafobia','pánico con agorafobia'],code:'F40.01',label:'Agorafobia con trastorno de pánico'},
 {terms:['trastorno de panico','trastorno de pánico'],code:'F41.0',label:'Trastorno de pánico [ansiedad paroxística episódica]'},
 {terms:['esquizofrenia'],code:'F20.9',label:'Esquizofrenia, no especificada'},
 {terms:['trastorno esquizoafectivo','esquizoafectivo'],code:'F25.9',label:'Trastorno esquizoafectivo, no especificado'},
 {terms:['trastorno bipolar'],code:'F31.9',label:'Trastorno bipolar, no especificado'},
 {terms:['ansiedad generalizada'],code:'F41.1',label:'Trastorno de ansiedad generalizada'},
 {terms:['trastorno obsesivo compulsivo','toc'],code:'F42.9',label:'Trastorno obsesivo-compulsivo, no especificado'},
 {terms:['trastorno limite de la personalidad','trastorno límite de la personalidad','tlp'],code:'F60.3',label:'Trastorno límite de la personalidad'}
];
const meds=[['escitalopram',['escitalopram','cipralex']],['fluoxetina',['fluoxetina','prozac']],['mirtazapina',['mirtazapina','rexer']],['lorazepam',['lorazepam','orfidal']],['sertralina',['sertralina','besitran']],['venlafaxina',['venlafaxina','vandral']],['duloxetina',['duloxetina','cymbalta']],['vortioxetina',['vortioxetina','brintellix']],['aripiprazol',['aripiprazol','abilify']],['olanzapina',['olanzapina','zyprexa']],['risperidona',['risperidona','risperdal']],['paliperidona',['paliperidona','xeplion','trevicta','byannli']],['quetiapina',['quetiapina','seroquel']],['clozapina',['clozapina','leponex']],['litio',['litio','plenur']],['valproato',['valproato','depakine']],['lamotrigina',['lamotrigina','lamictal']]];
function renderClinicalControl(text){const n=normalize(`${text} ${reportText()}`);const ds=diagnosisMap.filter(d=>d.terms.some(t=>n.includes(normalize(t))));$('#diagnosisSuggestions').innerHTML=ds.length?ds.map(d=>`<div class="suggestion"><strong>${d.code}</strong> — ${escapeHtml(d.label)}<div class="small">Sugerencia editable. Validar en eCIEMaps y según criterios clínicos.</div></div>`).join(''):'<p class="small">No hay una sugerencia CIE conservadora a partir del texto.</p>';
 const found=[];meds.forEach(([g,a])=>{const hit=a.find(x=>n.includes(normalize(x)));if(hit)found.push([g,hit])});$('#medSuggestions').innerHTML=found.length?found.map(x=>`<div class="suggestion"><strong>${escapeHtml(x[0])}</strong><span class="badge">${escapeHtml(x[1])}</span></div>`).join(''):'<p class="small">No se han detectado psicofármacos del diccionario local.</p>';
 const miss=[];if(!/autolit|suicid|autoagres|riesgo/.test(n))miss.push('No consta de forma explícita una valoración de riesgo autolítico/autoagresivo.');if($('#tipo').value==='initial'&&!/durante|desde hace|semanas|meses|dias|días/.test(n))miss.push('La cronología/duración del síndrome no está claramente expresada.');if(/depres/.test(n)&&!/semanas|dias|días|meses/.test(n))miss.push('En clínica depresiva conviene explicitar duración del síndrome para contrastar criterios temporales.');if(/panico|pánico/.test(n)&&!/inesperad|evitacion|evitación|preocupacion|preocupación/.test(n))miss.push('En pánico, revisar si las crisis son inesperadas y la preocupación/cambio conductual posterior.');$('#missingSuggestions').innerHTML=miss.length?miss.map(x=>`<div class="suggestion">${escapeHtml(x)}</div>`).join(''):'<div class="notice ok">Sin vacíos básicos detectados por las reglas actuales.</div>'}

const therapySources={
 niceDep:{name:'NICE NG222 — Depression in adults',url:'https://www.nice.org.uk/guidance/ng222/chapter/Recommendations'},
 nicePanic:{name:'NICE CG113 — GAD and panic disorder',url:'https://www.nice.org.uk/guidance/cg113/chapter/Recommendations'},
 nicePsychosis:{name:'NICE CG178 — Psychosis and schizophrenia',url:'https://www.nice.org.uk/guidance/cg178/chapter/recommendations'},
 niceBPD:{name:'NICE CG78 — Borderline personality disorder',url:'https://www.nice.org.uk/guidance/cg78/chapter/Recommendations'},
 niceBipolar:{name:'NICE CG185 — Bipolar disorder',url:'https://www.nice.org.uk/guidance/cg185/chapter/recommendations'},
 niceAlcohol:{name:'NICE CG115 — Alcohol-use disorders',url:'https://www.nice.org.uk/guidance/cg115/chapter/Recommendations'},
 elia:{name:'Elia Roca — materiales de habilidades sociales/asertividad',url:'https://eliarocapsicologa.wordpress.com/como-mejorar-tus-habilidades-sociales/'},
 moritz:{name:'Metacognitive Training for Psychosis — Moritz et al.',url:'https://clinical-neuropsychology.de/metacognitive_training-psychosis/'},
 moritzReview:{name:'Moritz et al. — MCT for psychosis: past, present and future (open access)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC8956140/'},
 matrix:{name:'e-Drogas / Modelo Matrix',url:'https://www.e-drogas.es/edrogas/portal/matrix.jsf'},
 jacobson:{name:'Servicio Andaluz de Salud — Relajación muscular progresiva de Jacobson',url:'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/sites/default/files/sincfiles/wsas-media-pdf_publicacion/2020/anexo_11_relajacion_muscular_progresiva.pdf'},
 sleep:{name:'Servicio Andaluz de Salud — Higiene del sueño',url:'https://www.sspa.juntadeandalucia.es/servicioandaluzdesalud/hrs3/fileadmin/user_upload/area_medica/neurofisiologia/higiene_sueno.pdf'},
 stepps:{name:'STEPPS — revisión/ensayo clínico',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC3608469/'},
 kabat:{name:'Jon Kabat-Zinn — Mindfulness en la vida cotidiana (referencia editorial)',url:'https://www.planetadelibros.com/libro-mindfulness-en-la-vida-cotidiana/342571'},
 gaslighting:{name:'Clinical Psychology Review — revisión histórica sobre gaslighting (2026)',url:'https://www.sciencedirect.com/science/article/pii/S0272735826000516'}
};
const therapyModules=[
 {id:'panic',title:'Pánico/agorafobia: exposición graduada + formulación CBT',tags:['panico','pánico','agorafobia','crisis de angustia','evitacion','evitación'],level:'Guía clínica',badge:'evidence',sources:['nicePanic'],why:'Útil cuando predominan crisis de pánico, evitación situacional y pérdida de autonomía.',steps:['Revisar el círculo miedo a sensaciones → interpretación amenazante → evitación/conductas de seguridad.','Construir una jerarquía breve de 5–8 situaciones evitadas, valorando malestar esperado.','Elegir una exposición alcanzable y repetirla sin escapar prematuramente; registrar predicción y resultado.','Revisar qué aprendió de la discrepancia entre lo temido y lo ocurrido.'],homework:'Tarea: repetir 3–5 veces la misma exposición elegida y anotar ansiedad inicial, máxima, final y aprendizaje.',plan:'Próxima sesión: revisar exposición graduada, conductas de seguridad y autoinstrucciones; avanzar un peldaño si hay aprendizaje suficiente.'},
 {id:'relax',title:'Ansiedad/estrés: relajación muscular progresiva',tags:['ansiedad','estres','estrés','tension','tensión','nerviosismo','crisis'],level:'Material institucional',badge:'evidence',sources:['jacobson'],why:'Habilidad complementaria para reconocer y reducir activación fisiológica; no debe convertirse en requisito para afrontar situaciones evitadas.',steps:['Explicar la diferencia entre tensión y relajación muscular.','Entrenar secuencias breves de tensar unos segundos y soltar cada grupo muscular, sin producir dolor.','Dirigir la atención a la sensación posterior de distensión.','Practicar primero en un entorno tranquilo y después usar una versión abreviada en situaciones cotidianas.'],homework:'Tarea: práctica diaria breve, registrando tensión subjetiva antes y después.',plan:'Puede consignarse: se entrena relajación muscular progresiva y se facilita práctica domiciliaria.'},
 {id:'depression',title:'Depresión/inhibición: activación conductual',tags:['depres','anhedonia','apatia','apatía','abulia','aislamiento','inhibid','abandono de actividades'],level:'Guía clínica',badge:'evidence',sources:['niceDep'],why:'Especialmente indicada cuando hay retirada social, inactividad o abandono de actividades significativas.',steps:['Mapear durante una semana actividad, evitación y estado de ánimo sin exigir “tener ganas”.','Elegir una actividad de dominio y una de disfrute de dificultad baja-moderada.','Programarlas con día/hora concreta y anticipar obstáculos.','Revisar resultado por conducta realizada, no solo por mejoría inmediata del ánimo.'],homework:'Tarea: dos acciones concretas y registrables antes de la siguiente sesión.',plan:'Próxima sesión: revisar actividad–ánimo, reforzar aproximaciones y aumentar gradualmente tareas significativas.'},
 {id:'cbtThoughts',title:'Cogniciones depresivas/ansiosas: registro y reencuadre CBT',tags:['culpa','minusvalia','minusvalía','catastrof','pensamiento negativo','cognicion','cognición','rumiacion','rumiación'],level:'CBT / apoyo profesional',badge:'evidence',sources:['niceDep'],why:'Para pensamientos automáticos negativos o interpretaciones catastróficas con repercusión emocional/conductual.',steps:['Seleccionar una situación reciente y concreta.','Separar situación, pensamiento/imagen, emoción, conducta y consecuencia.','Examinar evidencia a favor/en contra y detectar sesgos.','Construir una interpretación alternativa creíble y probarla mediante una pequeña acción/experimento.'],homework:'Tarea: completar 1–2 registros breves y traer el más relevante.',plan:'Próxima sesión: revisar un pensamiento diana y diseñar un experimento conductual pequeño.'},
 {id:'psychosis',title:'Psicosis: metacognición + CBTp centrada en malestar',tags:['psicosis','esquizofrenia','delirio','delirante','paranoia','alucin','voces','ideas de referencia'],level:'Guía + programa manualizado',badge:'evidence',sources:['nicePsychosis','moritz'],why:'Permite trabajar sesgos de razonamiento y afrontamiento sin confrontar directamente la creencia.',steps:['Partir del malestar o problema funcional que la persona quiere cambiar.','Explorar cómo llegamos a conclusiones y la posibilidad de “saltar a conclusiones” o buscar solo evidencia confirmatoria.','Generar al menos dos explicaciones alternativas y puntuar confianza, sin exigir renunciar a la explicación original.','Acordar una prueba segura y cotidiana para obtener nueva información.'],homework:'Tarea: identificar una situación en la que una primera interpretación cambió al disponer de más datos.',plan:'Próxima sesión: ejercicio metacognitivo sobre flexibilidad de conclusiones/atribuciones y estrategia de afrontamiento del síntoma diana.'},
 {id:'substances',title:'Consumo: entrevista motivacional + prevención de recaídas Matrix',tags:['consumo','cannabis','alcohol','cocaina','cocaína','estimulantes','abstinencia','recaida','recaída','craving'],level:'Guía + manual institucional',badge:'evidence',sources:['niceAlcohol','matrix'],why:'Útil para ambivalencia, mantenimiento de abstinencia, identificación de disparadores y prevención de recaídas.',steps:['Preguntar por importancia/confianza para el cambio y elicitar razones propias, evitando confrontación.','Explorar ventajas/inconvenientes de mantener el patrón y de cambiarlo.','Identificar disparadores externos e internos y la cadena pensamiento–emoción–conducta.','Definir una respuesta concreta ante craving y un contacto/recurso de apoyo.'],homework:'Tarea: registrar disparador, intensidad de craving, respuesta utilizada y resultado.',plan:'Próxima sesión: revisar motivación, disparadores y plan de respuesta; reforzar discurso de cambio y autoeficacia.'},
 {id:'assertiveness',title:'Asertividad y límites: petición, negativa y ensayo de conducta',tags:['asertiv','limites','límites','conflicto','familia','pareja','decir no','habilidades sociales','sumision','sumisión','agresiv'],level:'Material profesional',badge:'evidence',sources:['elia'],why:'Para dificultades en expresar necesidades, poner límites o equilibrar inhibición/agresividad.',steps:['Definir una situación interpersonal concreta y el objetivo legítimo.','Distinguir conducta inhibida, agresiva y asertiva.','Preparar un mensaje breve: hecho observable + efecto/necesidad + petición o límite.','Ensayar en sesión, invertir roles y ajustar tono, postura y repetición calmada.'],homework:'Tarea: realizar una petición o límite de dificultad baja y registrar resultado.',plan:'Próxima sesión: ensayo de conducta asertiva y revisión de creencias que dificultan decir no o pedir.'},
 {id:'sleep',title:'Insomnio: higiene del sueño + regularidad conductual',tags:['insomnio','sueño','despertar precoz','duerme mal','dormir'],level:'Material institucional',badge:'evidence',sources:['sleep'],why:'Píldora psicoeducativa básica cuando aparecen horarios irregulares o hábitos que perpetúan el insomnio.',steps:['Fijar hora estable de levantarse y limitar variaciones entre días.','Reducir tiempo despierto prolongado en cama y evitar siestas largas.','Revisar cafeína, nicotina, alcohol y pantallas/activación nocturna.','Crear rutina breve de desaceleración y ambiente de sueño adecuado.'],homework:'Tarea: diario de sueño simple durante 7 días.',plan:'Próxima sesión: revisar diario y seleccionar 1–2 cambios conductuales prioritarios.'},
 {id:'mindfulness',title:'Mindfulness: atención al presente y descentramiento',tags:['mindfulness','rumiacion','rumiación','estres','estrés','ansiedad flotante','reactividad'],level:'Intervención complementaria',badge:'formulation',sources:['kabat'],why:'Puede utilizarse como práctica breve de atención y descentramiento cuando la persona tolera bien focalizarse en la experiencia interna.',steps:['Adoptar postura estable y dirigir atención a respiración/sensaciones durante 2–5 minutos.','Cuando aparezca un pensamiento, etiquetarlo de forma sencilla (“pensamiento”, “preocupación”) sin discutirlo.','Volver deliberadamente al anclaje elegido.','Cerrar identificando una acción consciente inmediata en lugar de continuar en piloto automático.'],homework:'Tarea: práctica breve diaria y registrar si aumenta o disminuye malestar; suspender/adaptar si resulta desorganizadora.',plan:'Próxima sesión: practicar atención breve al presente y trabajar relación con pensamientos, no su eliminación.'},
 {id:'bpd',title:'Disregulación/TLP: habilidad DBT/STEPPS focal',tags:['tlp','trastorno limite','trastorno límite','disregul','impulsiv','autoles','autoagres','intensidad emocional','abandono'],level:'Programa basado en evidencia',badge:'evidence',sources:['niceBPD','stepps'],why:'Para entrenamiento de habilidades dentro de un plan estructurado. No sustituye una psicoterapia específica completa.',steps:['Nombrar la emoción y puntuar intensidad de 0–5/10 antes de actuar.','Separar emoción, impulso y conducta; identificar el punto temprano donde aún hay opciones.','Elegir una habilidad concreta: pausa/distanciamiento, comunicación, distracción segura o resolución de problemas.','Revisar consecuencias a corto y largo plazo y reforzar conducta eficaz.'],homework:'Tarea: registrar un episodio de intensidad emocional con antecedente, impulso, habilidad usada y resultado.',plan:'Próxima sesión: entrenamiento de una habilidad de regulación/interpersonal. Si el objetivo principal es autolesión recurrente, valorar programa DBT completo según disponibilidad.'},
 {id:'family',title:'Familia: límites, triangulación y resolución colaborativa',tags:['familia','triangul','madre','padre','pareja','emocion expresada','emoción expresada','delegacion','delegación','sobreproteccion','sobreprotección'],level:'Formulación / intervención familiar',badge:'formulation',sources:['nicePsychosis'],why:'Útil cuando el patrón relacional mantiene estrés, dependencia, sobreinvolucración o conflicto.',steps:['Mapear quién habla con quién cuando aparece el problema y qué función cumple un tercero.','Reformular el patrón como problema del sistema, evitando buscar culpables.','Clarificar qué responsabilidades pertenecen al paciente y cuáles al familiar.','Acordar una comunicación directa y una pequeña regla de límites/ayuda revisable.'],homework:'Tarea: observar un episodio familiar sin intervenir automáticamente y registrar secuencia y resultado.',plan:'Próxima sesión: recuadre de roles/límites y resolución negociada de un problema concreto.'},
 {id:'gaslighting',title:'Gaslighting: validación, contraste y recuperación de agencia',tags:['gaslighting','gas light','ghost lightning','manipulacion','manipulación','duda de si misma','duda de sí misma'],level:'Formulación clínica emergente',badge:'formulation',sources:['gaslighting'],why:'Cuando existe un patrón relacional de invalidación/manipulación que erosiona confianza en la propia percepción. No es un diagnóstico.',steps:['Validar el impacto emocional sin confirmar automáticamente interpretaciones no verificadas.','Separar hechos observables, interpretaciones propias y mensajes de la otra persona.','Explorar aislamiento, coerción, control y seguridad; si hay violencia, priorizar evaluación y recursos específicos.','Recuperar agencia mediante decisiones pequeñas, red de apoyo y límites claros.'],homework:'Tarea: registro breve de situaciones con hecho observable, mensaje recibido, respuesta propia y alternativa elegida.',plan:'Próxima sesión: contraste de hechos/interpretaciones, fortalecimiento de agencia y revisión de seguridad relacional.'},
 {id:'medPsychoed',title:'Píldora psicoeducativa: papel de la medicación',tags:['medicacion','medicación','adherencia','antidepresivo','antipsicotico','antipsicótico','efectos secundarios','abandono tratamiento'],level:'Psicoeducación',badge:'formulation',sources:[],why:'Para mejorar comprensión, expectativas realistas y adherencia compartida.',steps:['Preguntar qué entiende la persona que pretende conseguir la medicación.','Explicar objetivo, latencia esperable y qué síntomas no necesariamente resuelve por sí sola.','Revisar efectos adversos, preocupaciones y barreras reales de adherencia.','Acordar qué observar hasta la siguiente visita y cuándo consultar antes.'],homework:'Tarea: anotar beneficio percibido, efecto adverso o duda relevante para revisar en consulta.',plan:'Próxima sesión: psicoeducación breve sobre objetivos/limitaciones del tratamiento y decisión compartida.'}
];
function sourceHtml(ids){if(!ids.length)return '<div class="source">Fuente: formulación clínica / psicoeducación general.</div>';return `<div class="source">Fuentes: ${ids.map(id=>{const s=therapySources[id];return `<a href="${s.url}" target="_blank" rel="noopener noreferrer">${escapeHtml(s.name)}</a>`}).join(' · ')}</div>`}
function therapyCard(m){return `<div class="therapy-card" data-module="${m.id}"><h4>${escapeHtml(m.title)} <span class="badge ${m.badge}">${escapeHtml(m.level)}</span></h4><div class="why">${escapeHtml(m.why)}</div><ol class="steps">${m.steps.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol><div class="small"><b>${escapeHtml(m.homework)}</b></div>${sourceHtml(m.sources)}<div class="therapy-actions"><button class="secondary" data-copy="${m.id}">Copiar propuesta</button><button class="secondary" data-plan="${m.id}">Añadir frase al plan</button></div></div>`}
function matchModules(text){const n=normalize(text);const scored=therapyModules.map(m=>({m,score:m.tags.reduce((a,t)=>a+(n.includes(normalize(t))?2:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);const out=[];for(const x of scored){if(!out.some(y=>y.id===x.m.id))out.push(x.m);if(out.length>=6)break}return out}
function renderTherapy(text){const mods=matchModules(`${contextText()} ${text} ${reportText()}`);$('#therapySummary').textContent=mods.length?`Se han seleccionado ${mods.length} propuestas según los problemas descritos. Prioriza 1–2 por sesión.`:'No se han detectado dianas claras. Puedes buscar manualmente en la biblioteca de técnicas.';$('#therapyCards').innerHTML=mods.map(therapyCard).join('');bindTherapyButtons()}
function bindTherapyButtons(){$$('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{const m=therapyModules.find(x=>x.id===b.dataset.copy);const txt=`${m.title}\n\n${m.steps.map((x,i)=>`${i+1}. ${x}`).join('\n')}\n\n${m.homework}\n\n${m.plan}`;try{await navigator.clipboard.writeText(txt);alert('Propuesta copiada.')}catch{alert(txt)}}));$$('[data-plan]').forEach(b=>b.addEventListener('click',()=>{const m=therapyModules.find(x=>x.id===b.dataset.plan);const sec=currentSections.find(x=>/Plan de tratamiento|Intervención de Psicología|Plan de tratamiento e intervención/i.test(x));if(!sec)return alert('No hay un apartado de plan compatible en el informe actual.');currentReport[sec]=`${currentReport[sec]||''}${currentReport[sec]?'\n':''}${m.plan}`;renderReport();alert('Añadido como borrador al plan. Revísalo antes de usarlo.')}))}
function renderTherapyLibrary(query=''){const n=normalize(query);const mods=n?therapyModules.filter(m=>normalize(`${m.title} ${m.tags.join(' ')} ${m.why}`).includes(n)||m.tags.some(t=>normalize(t).includes(n))):therapyModules;$('#therapyLibrary').innerHTML=mods.slice(0,12).map(therapyCard).join('');bindTherapyButtons()}
$('#therapyFilter').addEventListener('input',e=>renderTherapyLibrary(e.target.value));renderTherapyLibrary();


// ===== TERAPIA GRUPAL TMG =====
const groupCycles={
 mixed:{
  name:'TMG mixto — recuperación y habilidades (12 sesiones)',
  description:'Ciclo transdiagnóstico para un grupo rehabilitador heterogéneo. Prioriza recuperación, funcionamiento, autorregulación y prevención de recaídas.',
  sessions:[
   {title:'1. Recuperación: qué significa estar mejor',goals:['Definir recuperación más allá de la desaparición de síntomas.','Identificar una meta funcional pequeña y significativa.'],teach:'Diferenciar síntomas, funcionamiento y proyecto vital. Normalizar que la recuperación puede ser no lineal.',exercise:'Rueda de áreas: cada participante elige, sin obligación de revelar detalles, un área que quiere recuperar (rutina, relaciones, actividad, autonomía, ocio). Convertirla en un objetivo pequeño y observable.',task:'Elegir una acción de 10–30 minutos relacionada con esa meta antes de la siguiente sesión.',sources:['nicePsychosis','niceBipolar','niceDep']},
   {title:'2. Estrés, vulnerabilidad y señales tempranas',goals:['Relacionar estrés, sueño, hábitos y síntomas.','Reconocer señales tempranas personales sin alarmismo.'],teach:'Modelo estrés-vulnerabilidad como marco explicativo, no como culpa. Diferenciar señal temprana de recaída establecida.',exercise:'Semáforo grupal: ejemplos anónimos de señales verdes, ámbar y rojas; construir respuestas proporcionadas para cada nivel.',task:'Observar una señal de bienestar y una señal de sobrecarga durante los próximos días.',sources:['nicePsychosis','niceBipolar']},
   {title:'3. Rutinas, activación y funcionamiento',goals:['Comprender el vínculo actividad–ánimo–función.','Reducir el patrón de espera a “tener ganas”.'],teach:'Activación conductual y graduación de tareas: empezar por conductas manejables y significativas.',exercise:'Diseñar una escalera de actividad de 3 peldaños: mínima, intermedia y objetivo.',task:'Realizar el primer peldaño y registrar qué facilitó o dificultó hacerlo.',sources:['niceDep']},
   {title:'4. Comunicación: pasivo, agresivo y asertivo',goals:['Distinguir estilos de comunicación.','Practicar una respuesta asertiva breve.'],teach:'Asertividad como defensa de derechos y necesidades respetando las de los demás.',exercise:'Tarjetas de situaciones cotidianas. En parejas, representar respuesta pasiva, agresiva y asertiva; el grupo identifica diferencias.',task:'Probar una petición sencilla o expresar una preferencia de forma directa.',sources:['elia']},
   {title:'5. Decir no y poner límites',goals:['Practicar negativas breves sin sobrejustificación.','Detectar creencias que dificultan poner límites.'],teach:'Límite claro, breve y repetible; diferenciar culpa de responsabilidad.',exercise:'Role-play “disco rayado”: negativa breve + validación + repetición calmada.',task:'Ensayar un límite de dificultad baja en una situación segura.',sources:['elia']},
   {title:'6. Emociones: identificar antes de actuar',goals:['Nombrar emoción e intensidad.','Separar emoción, impulso y conducta.'],teach:'Las emociones aportan información, pero no obligan a actuar de una forma concreta.',exercise:'Cadena ABC simplificada: situación → emoción/impulso → conducta → consecuencia. Buscar un punto donde introducir una pausa.',task:'Registrar una emoción intensa y qué opción apareció al introducir una pausa.',sources:['stepps','niceBPD']},
   {title:'7. Relajación muscular y reducción de activación',goals:['Reconocer tensión corporal.','Aprender una versión breve de relajación muscular progresiva.'],teach:'Principio tensión–distensión de Jacobson y uso como habilidad de regulación, no como conducta de seguridad obligatoria.',exercise:'Práctica guiada breve por grupos musculares, evitando dolor; cierre comparando tensión subjetiva antes/después.',task:'Practicar una versión breve una vez al día si resulta útil.',sources:['jacobson']},
   {title:'8. Pensamiento flexible: no concluir demasiado pronto',goals:['Normalizar sesgos cognitivos universales.','Practicar generación de explicaciones alternativas.'],teach:'Introducción metacognitiva: todos cometemos errores de razonamiento; más información puede cambiar una conclusión.',exercise:'Viñetas ambiguas: formular tres explicaciones posibles antes de decidir qué ocurrió y qué dato faltaría.',task:'Detectar una ocasión cotidiana en la que una primera impresión cambió con información nueva.',sources:['moritz','moritzReview']},
   {title:'9. Sueño y ritmo diario',goals:['Identificar hábitos que alteran el sueño.','Seleccionar uno o dos cambios realistas.'],teach:'Regularidad de horarios, reducción de activación nocturna y hábitos básicos de sueño.',exercise:'“Auditoría” grupal de hábitos: clasificar conductas en ayudan / interfieren / depende.',task:'Mantener durante varios días un único cambio acordado y observar resultado.',sources:['sleep']},
   {title:'10. Motivación y ambivalencia ante cambios',goals:['Explorar pros y contras sin confrontación.','Aumentar lenguaje de cambio y autoeficacia.'],teach:'Principios de entrevista motivacional: autonomía, evocación de razones propias y discrepancia con objetivos personales.',exercise:'Balanza decisional sobre un cambio genérico de salud o funcionamiento; después escala importancia/confianza 0–10.',task:'Dar un paso que aumente un punto la confianza en el cambio elegido.',sources:['matrix']},
   {title:'11. Resolver problemas paso a paso',goals:['Evitar pasar directamente de problema a bloqueo.','Practicar generación y selección de alternativas.'],teach:'Definir problema concreto, generar opciones, valorar pros/contras, elegir prueba pequeña y revisar.',exercise:'Resolver en grupo un caso ficticio cotidiano siguiendo seis pasos, sin usar problemas identificables de participantes.',task:'Aplicar el esquema a un problema pequeño y revisable.',sources:['niceBipolar','nicePsychosis']},
   {title:'12. Plan de bienestar y prevención de recaídas',goals:['Integrar habilidades aprendidas.','Construir un plan personal de mantenimiento y petición de ayuda.'],teach:'Reconocer factores protectores, señales tempranas, habilidades útiles y vías de apoyo.',exercise:'Plantilla “me mantiene bien / señales de alerta / qué hago / a quién aviso”, compartiendo solo lo que cada persona quiera.',task:'Conservar y revisar el plan de bienestar con el equipo de referencia.',sources:['nicePsychosis','niceBipolar']}
  ]
 },
 assertiveness:{name:'Asertividad y habilidades sociales (8 sesiones)',description:'Entrenamiento progresivo en comunicación, límites y ensayo conductual.',sessions:[
  {title:'1. Qué es ser asertivo',goals:['Distinguir pasividad, agresividad y asertividad.','Identificar derechos y necesidades legítimas.'],teach:'Asertividad como autoafirmación y expresión adecuada, respetando a la otra persona.',exercise:'Clasificar respuestas de ejemplos ficticios en pasiva/agresiva/asertiva y reformularlas.',task:'Observar un ejemplo cotidiano de cada estilo.',sources:['elia']},
  {title:'2. Expresar necesidades y hacer peticiones',goals:['Formular peticiones concretas.','Reducir mensajes vagos o acusatorios.'],teach:'Hecho observable + necesidad/efecto + petición concreta.',exercise:'Transformar frases generales (“nunca me ayudas”) en peticiones observables y negociables.',task:'Realizar una petición de dificultad baja.',sources:['elia']},
  {title:'3. Decir no sin sobrejustificarse',goals:['Practicar negativa breve.','Tolerar malestar o culpa tras poner un límite.'],teach:'Negarse no requiere convencer al otro; validar no equivale a ceder.',exercise:'Role-play con “disco rayado” y cambio de roles.',task:'Ensayar una negativa segura.',sources:['elia']},
  {title:'4. Expresar desacuerdo',goals:['Discrepar sin atacar.','Mantener tono y contenido separados.'],teach:'Opinión propia en primera persona, argumento breve y apertura a negociar.',exercise:'Debate de temas neutros con reglas de desacuerdo asertivo.',task:'Expresar una opinión diferente en contexto de bajo riesgo.',sources:['elia']},
  {title:'5. Recibir críticas',goals:['Diferenciar crítica útil, parcial e injusta.','Responder sin defensividad automática.'],teach:'Preguntar, concretar, admitir la parte cierta y poner límite a descalificaciones.',exercise:'Banco de niebla / acuerdo parcial con ejemplos neutros.',task:'Registrar una crítica y qué parte era información útil.',sources:['elia']},
  {title:'6. Hacer críticas y pedir cambios',goals:['Describir conducta, no etiquetar persona.','Pedir un cambio realista.'],teach:'Conducta concreta + impacto + petición + consecuencia negociable.',exercise:'Reformular acusaciones en mensajes específicos.',task:'Preparar por escrito una petición de cambio.',sources:['elia']},
  {title:'7. Límites en familia y pareja',goals:['Diferenciar ayuda de sobreimplicación.','Practicar límites consistentes.'],teach:'Responsabilidad propia vs ajena; límites como reglas de interacción, no castigo.',exercise:'Casos ficticios de sobreprotección, triangulación y conflicto; proponer límite y comunicación directa.',task:'Elegir un límite pequeño que dependa de la propia conducta.',sources:['elia','nicePsychosis']},
  {title:'8. Integración y role-play',goals:['Combinar petición, negativa, crítica y desacuerdo.','Identificar habilidades a seguir practicando.'],teach:'Repaso de estructura de mensajes asertivos y regulación del tono.',exercise:'Circuito de role-play con situaciones graduadas elegidas de una lista neutra.',task:'Plan individual de una habilidad a practicar durante el próximo mes.',sources:['elia']}
 ]},
 metacognition:{name:'Metacognición y flexibilidad cognitiva (8 sesiones)',description:'Inspirado en MCT de Moritz para trabajar sesgos de razonamiento de manera normalizadora y no confrontativa.',sessions:[
  {title:'1. Todos tenemos “trampas” de pensamiento',goals:['Normalizar sesgos cognitivos.','Introducir actitud de curiosidad sobre las propias conclusiones.'],teach:'El objetivo no es “pensar bien siempre”, sino detectar cuándo conviene frenar y buscar más información.',exercise:'Ilusiones/viñetas ambiguas descritas verbalmente: primera impresión y revisión con nuevos datos.',task:'Anotar una situación donde cambió de opinión al conocer más información.',sources:['moritz','moritzReview']},
  {title:'2. Saltar a conclusiones',goals:['Detectar decisiones con poca evidencia.','Practicar pedir un dato adicional.'],teach:'Más seguridad subjetiva no siempre significa más evidencia.',exercise:'Historias en tres pasos: votar hipótesis tras cada dato y observar cambios.',task:'Antes de una conclusión importante, formular “¿qué dato me falta?”.',sources:['moritz','moritzReview']},
  {title:'3. Atribuciones: por qué pasan las cosas',goals:['Generar causas múltiples.','Evitar atribuciones únicas automáticas.'],teach:'Una conducta suele tener causas personales, situacionales y relacionales.',exercise:'Casos ficticios: generar al menos una explicación interna, una externa y una mixta.',task:'Buscar dos explicaciones alternativas a un malentendido cotidiano.',sources:['moritz']},
  {title:'4. Confianza y posibilidad de error',goals:['Graduar certeza.','Tolerar “no lo sé todavía”.'],teach:'Trabajar con probabilidades permite revisar una conclusión sin sentirse invalidado.',exercise:'Escala 0–100 de confianza antes/después de recibir nueva información.',task:'Usar una escala de confianza ante una interpretación que genere malestar.',sources:['moritz','moritzReview']},
  {title:'5. Cognición social y lectura de intenciones',goals:['Diferenciar señal observable de intención inferida.','Generar alternativas sociales.'],teach:'La mente completa huecos rápidamente, sobre todo con estrés.',exercise:'Escenas sociales ambiguas ficticias: ¿qué sabemos?, ¿qué inferimos?, ¿qué preguntaríamos?',task:'Separar en una situación “hecho observado” e “interpretación”.',sources:['moritz']},
  {title:'6. Memoria y reconstrucción',goals:['Comprender que la memoria no es una grabación literal.','Reducir exceso de confianza en recuerdos incompletos.'],teach:'Recordar implica reconstruir; lagunas pueden llenarse de forma plausible pero incorrecta.',exercise:'Relato breve y recuerdo diferido; comparar detalles seguros, dudosos y añadidos.',task:'Cuando un recuerdo sea relevante, distinguir “seguro / probable / no sé”.',sources:['moritz']},
  {title:'7. Autoestima y estigma',goals:['Separar identidad de diagnóstico.','Identificar generalizaciones negativas sobre uno mismo.'],teach:'Una dificultad o diagnóstico no define capacidades, valores ni todas las áreas de funcionamiento.',exercise:'Inventario de roles, fortalezas y logros no relacionados con enfermedad; reformular etiquetas globales.',task:'Realizar una acción coherente con una fortaleza identificada.',sources:['moritz','nicePsychosis']},
  {title:'8. Integración: pensar con flexibilidad',goals:['Repasar herramientas.','Elegir una estrategia metacognitiva personal.'],teach:'Pausa, buscar datos, generar alternativas, graduar confianza y revisar.',exercise:'Resolver en grupo tres situaciones ficticias usando la secuencia completa.',task:'Elegir una pregunta recordatorio: “¿qué otra explicación hay?” o “¿qué dato falta?”.',sources:['moritz','moritzReview']}
 ]},
 emotion:{name:'Regulación emocional y habilidades (8 sesiones)',description:'Microhabilidades inspiradas en CBT/STEPPS/DBT, sin sustituir un programa estructurado específico.',sessions:[
  {title:'1. Para qué sirven las emociones',goals:['Normalizar emociones.','Distinguir emoción de conducta.'],teach:'Las emociones son señales; intensidad y utilidad pueden no coincidir.',exercise:'Tarjetas emoción–función–impulso–respuesta alternativa.',task:'Nombrar emoción e intensidad 0–10 una vez al día.',sources:['stepps','niceBPD']},
  {title:'2. Detectar el punto de subida',goals:['Reconocer señales corporales y cognitivas.','Intervenir antes del pico.'],teach:'Cuanto antes se detecta la escalada, más opciones conductuales suelen existir.',exercise:'Dibujar una curva de activación ficticia e identificar puntos de intervención.',task:'Registrar una señal temprana de activación.',sources:['stepps']},
  {title:'3. Pausa y tolerancia al malestar',goals:['Introducir una demora entre impulso y acción.','Elegir conducta segura a corto plazo.'],teach:'Tolerar malestar no significa aprobar la situación; significa no empeorarla mientras baja la intensidad.',exercise:'Secuencia parar–observar–elegir con casos ficticios.',task:'Practicar una pausa breve ante malestar moderado.',sources:['stepps','niceBPD']},
  {title:'4. Activación y acción opuesta útil',goals:['Detectar evitación mantenedora.','Probar una acción compatible con objetivos.'],teach:'No todas las emociones deben guiar la conducta; a veces conviene actuar en dirección distinta al impulso.',exercise:'Elegir respuestas alternativas para tristeza, miedo e irritabilidad en ejemplos.',task:'Una acción pequeña contra un patrón de evitación.',sources:['niceDep','stepps']},
  {title:'5. Resolver problemas',goals:['Convertir problemas globales en concretos.','Generar varias respuestas.'],teach:'Definir, idear, elegir, probar y revisar.',exercise:'Problema ficticio grupal resuelto en pasos.',task:'Aplicar el esquema a una dificultad pequeña.',sources:['stepps','niceBipolar']},
  {title:'6. Límites interpersonales',goals:['Expresar necesidades y límites.','Reducir respuestas extremas de sumisión/ataque.'],teach:'Mensaje claro, validación y límite conductual.',exercise:'Role-play de petición y negativa.',task:'Practicar una frase de límite preparada.',sources:['elia','stepps']},
  {title:'7. Reparar después de un conflicto',goals:['Revisar conducta sin autocastigo.','Planificar reparación proporcional.'],teach:'Responsabilidad implica reconocer efecto, reparar cuando proceda y aprender; no exige descalificarse.',exercise:'Caso ficticio: distinguir disculpa, explicación, reparación y límite.',task:'Escribir un plan de reparación para un ejemplo hipotético.',sources:['elia','stepps']},
  {title:'8. Caja personal de habilidades',goals:['Seleccionar habilidades eficaces.','Preparar plan ante próxima escalada.'],teach:'Las habilidades funcionan mejor cuando se eligen antes del pico emocional.',exercise:'Cada participante selecciona 3 habilidades de un listado y ensaya cuándo usarlas.',task:'Conservar una tarjeta de habilidades personales.',sources:['stepps','niceBPD']}
 ]},
 anxiety:{name:'Ansiedad, estrés, relajación y mindfulness (8 sesiones)',description:'Ciclo transdiagnóstico de regulación fisiológica, afrontamiento y reducción de evitación.',sessions:[
  {title:'1. Entender la respuesta de ansiedad',goals:['Normalizar la activación fisiológica.','Distinguir peligro real de alarma interna.'],teach:'Ciclo situación–interpretación–activación–conducta y papel de la evitación.',exercise:'Construir en grupo un círculo de ansiedad con un caso ficticio.',task:'Identificar un disparador y la respuesta asociada.',sources:['nicePanic']},
  {title:'2. Relajación muscular progresiva',goals:['Detectar tensión.','Practicar tensión–distensión de forma segura.'],teach:'Principio básico de Jacobson y adaptación breve.',exercise:'Práctica guiada de grupos musculares sin dolor.',task:'Práctica breve diaria si resulta útil.',sources:['jacobson']},
  {title:'3. Atención al presente',goals:['Entrenar retorno voluntario de la atención.','Reducir fusión con preocupaciones.'],teach:'Observar pensamiento como evento mental y volver a un anclaje sensorial.',exercise:'Práctica de 3 minutos de respiración/sonidos/sensaciones con ojos abiertos o cerrados según preferencia.',task:'Práctica breve y registrar tolerancia.',sources:['kabat']},
  {title:'4. Preocupación vs problema resoluble',goals:['Distinguir rumiación/preocupación de resolución.','Elegir acción cuando existe control.'],teach:'Si hay una acción concreta, resolver; si no, practicar aceptación/retorno al presente.',exercise:'Clasificar ejemplos en problema resoluble / incertidumbre no controlable.',task:'Aplicar el criterio a una preocupación.',sources:['nicePanic']},
  {title:'5. Evitación y exposición gradual',goals:['Comprender cómo la evitación mantiene miedo.','Diseñar pasos graduales.'],teach:'Exposición como aprendizaje de nueva información, no como prueba de valentía.',exercise:'Construir una jerarquía ficticia de 5 pasos y discutir conductas de seguridad.',task:'Elegir una aproximación pequeña y segura a una actividad evitada, si está indicada individualmente.',sources:['nicePanic']},
  {title:'6. Autoinstrucciones útiles',goals:['Cambiar mensajes catastróficos por instrucciones operativas.','Evitar tranquilización absoluta.'],teach:'Frases breves centradas en tolerancia y acción: “puedo permanecer”, “esto sube y baja”, “voy paso a paso”.',exercise:'Reformular frases de pánico/estrés en autoinstrucciones realistas.',task:'Usar una autoinstrucción elegida en una situación moderada.',sources:['nicePanic']},
  {title:'7. Sueño y regulación',goals:['Identificar hábitos relacionados con insomnio.','Elegir cambios concretos.'],teach:'Regularidad, activación nocturna y hábitos de sueño.',exercise:'Clasificar hábitos y diseñar una rutina de desaceleración de 30–60 min.',task:'Mantener un cambio durante varios días.',sources:['sleep']},
  {title:'8. Plan personal de manejo del estrés',goals:['Integrar habilidades.','Elegir qué técnica usar según situación.'],teach:'No todas las técnicas sirven para todo: regulación, afrontamiento, exposición, solución de problemas y descanso tienen funciones diferentes.',exercise:'Casos: elegir técnica adecuada y justificar por qué.',task:'Plan de 3 señales + 3 respuestas + 1 apoyo.',sources:['nicePanic','jacobson','sleep']}
 ]},
 substances:{name:'Motivación y prevención de recaídas (8 sesiones)',description:'Basado en entrevista motivacional y componentes psicoeducativos del Modelo Matrix.',sessions:[
  {title:'1. Ambivalencia y razones para cambiar',goals:['Explorar sin confrontación.','Evocar razones propias.'],teach:'Autonomía, balanza decisional y lenguaje de cambio.',exercise:'Pros/contras de mantener y cambiar un hábito ficticio.',task:'Escala importancia/confianza y un paso para subir un punto.',sources:['matrix']},
  {title:'2. Disparadores externos e internos',goals:['Identificar antecedentes.','Distinguir disparador de decisión final.'],teach:'Personas/lugares/estados internos pueden aumentar probabilidad de consumo sin determinarla.',exercise:'Mapa ficticio de disparadores y alternativas.',task:'Observar un disparador y respuesta.',sources:['matrix']},
  {title:'3. Craving: ola que sube y baja',goals:['Normalizar craving.','Preparar respuestas concretas.'],teach:'Demora, cambio de contexto, apoyo, actividad incompatible y recordatorio de motivos.',exercise:'Construir una tarjeta de respuesta al craving.',task:'Ensayar la tarjeta ante craving leve/moderado si aparece.',sources:['matrix']},
  {title:'4. Pensamiento–emoción–conducta',goals:['Detectar cadenas automáticas.','Introducir alternativas.'],teach:'Un pensamiento de permiso puede ser un eslabón modificable.',exercise:'Completar cadenas con casos ficticios y encontrar puntos de corte.',task:'Registrar una cadena breve.',sources:['matrix']},
  {title:'5. Situaciones de alto riesgo',goals:['Anticipar escenarios.','Planificar salida y apoyo.'],teach:'Prevención funciona mejor antes de estar en el máximo riesgo.',exercise:'Plan “si X, entonces Y” para tres escenarios ficticios.',task:'Preparar un plan para una situación real no identificable.',sources:['matrix']},
  {title:'6. Red de recuperación y actividades',goals:['Aumentar alternativas al consumo.','Identificar apoyos.'],teach:'Recuperación requiere estructura, actividades y vínculos compatibles con objetivos.',exercise:'Mapa de apoyos por funciones, sin nombres propios.',task:'Activar un apoyo o actividad.',sources:['matrix']},
  {title:'7. Comunicación y familia',goals:['Pedir apoyo concreto.','Poner límites a situaciones de riesgo.'],teach:'Peticiones específicas y acuerdos realistas.',exercise:'Role-play de petición de apoyo y negativa.',task:'Practicar una comunicación de bajo riesgo.',sources:['matrix','elia']},
  {title:'8. Desliz vs recaída y plan de recuperación',goals:['Evitar pensamiento todo-o-nada.','Preparar respuesta rápida ante un desliz.'],teach:'Analizar lo ocurrido, reducir daño, reconectar con apoyos y reanudar plan.',exercise:'Caso ficticio de desliz: primeras 24 horas y aprendizaje.',task:'Conservar plan escrito de actuación.',sources:['matrix']}
 ]}
};

let currentGroupPlanText='';
function groupSourceHtml(ids){return sourceHtml(ids||[])}
function populateGroupCycles(){
 const cycle=$('#groupCycle');cycle.innerHTML=Object.entries(groupCycles).map(([id,c])=>`<option value="${id}">${escapeHtml(c.name)}</option>`).join('');
 populateGroupSessions();
}
function populateGroupSessions(){
 const c=groupCycles[$('#groupCycle').value]||groupCycles.mixed;
 $('#groupSession').innerHTML=c.sessions.map((x,i)=>`<option value="${i}">${escapeHtml(x.title)}</option>`).join('');
}
function groupPrivacyScan(text){
 const hits=privacyScan(text);
 if(/\b(?:inicial(?:es)?|paciente)\s+[A-ZÁÉÍÓÚÑ](?:\.|\b)/u.test(text))hits.push('inicial/código potencialmente vinculable');
 if(/\b(?:de\s+)?\d{1,2}\s+años\b/i.test(text))hits.push('edad exacta');
 if(/\b(?:vive|reside|trabaja)\s+en\b/i.test(text))hits.push('localización/entorno potencialmente identificable');
 return [...new Set(hits)];
}
function renderGroupPrivacy(text,target){
 const hits=groupPrivacyScan(text);
 $(target).innerHTML=hits.length?`<div class="notice danger"><b>Revisar minimización:</b> ${hits.map(escapeHtml).join(', ')}. En el histórico grupal usa solo observaciones colectivas.</div>`:'<div class="notice ok">Sin identificadores obvios detectados. Mantén el contenido a nivel de dinámica grupal.</div>';
 return hits;
}
function groupAdaptation(text){
 const n=normalize(text);const tips=[];
 if(/poco dinam|poca particip|silencio|pasiv|cuesta hablar|escasa particip/.test(n))tips.push('Priorizar parejas/tríadas, preguntas de elección y role-play breve antes de pedir puesta en común abierta.');
 if(/muy dinam|hablan mucho|interrump|desbord|monopol/.test(n))tips.push('Estructurar turnos, limitar intervenciones a 1 minuto y usar ronda obligatoria opcional de “paso”.');
 if(/cognitiv|dificultad de compren|lento|atencion|atención/.test(n))tips.push('Reducir carga verbal: una idea por vez, ejemplos concretos, repetición y apoyo visual sencillo.');
 if(/ansied|nervios|activacion|activación/.test(n))tips.push('Comenzar con 2–3 minutos de aterrizaje y explicar que cualquiera puede observar sin participar en ejercicios demasiado activadores.');
 if(/conflict|tension|tensión|discusion|discusión/.test(n))tips.push('Reforzar reglas de seguridad interpersonal: hablar desde la experiencia propia, no interpretar a otros y no usar ejemplos identificables del grupo.');
 if(/psicos|parano|delir|voces/.test(n))tips.push('Mantener formulación normalizadora y no confrontativa; trabajar procesos de razonamiento y malestar, no debatir la veracidad de creencias concretas en el grupo.');
 return tips;
}
function buildGroupPlan(){
 const cycle=groupCycles[$('#groupCycle').value]||groupCycles.mixed;
 const idx=Math.max(0,Math.min(cycle.sessions.length-1,Number($('#groupSession').value)||0));
 const sess=cycle.sessions[idx];const tone=$('#groupTone').value.trim();const hits=renderGroupPrivacy(tone,'#groupPrivacy');
 if(hits.length)return alert('Revisa el contexto del grupo antes de generar el guion. Evita iniciales y datos potencialmente vinculables.');
 const adaptations=groupAdaptation(tone);
 const sourceNames=(sess.sources||[]).map(id=>therapySources[id]?.name).filter(Boolean);
 currentGroupPlanText=`${cycle.name}\n${sess.title}\n\nOBJETIVOS\n- ${sess.goals.join('\n- ')}\n\nESTRUCTURA ORIENTATIVA (60 min)\n1. Apertura y encuadre (5 min): check-in breve y recordatorio de reglas de confidencialidad/respeto.\n2. Recuperación de la sesión previa (5 min): una idea o práctica que recuerden.\n3. Píldora psicoeducativa (10 min): ${sess.teach}\n4. Ejercicio principal (25 min): ${sess.exercise}\n5. Puesta en común y generalización (10 min): qué fue útil, qué costó y cómo llevarlo a situaciones cotidianas.\n6. Cierre (5 min): ${sess.task}\n${adaptations.length?`\nADAPTACIÓN AL TONO ACTUAL DEL GRUPO\n- ${adaptations.join('\n- ')}\n`:''}\nFUENTES / MARCO\n- ${sourceNames.join('\n- ')||'Formulación psicoterapéutica transdiagnóstica.'}\n\nNOTA DE SEGURIDAD\nEvitar trabajar en el grupo contenido individual altamente identificable, trauma detallado, riesgo agudo o creencias psicóticas específicas si la dinámica no permite un encuadre seguro. Derivar esos contenidos a valoración individual cuando proceda.`;
 $('#groupPlan').innerHTML=`<div class="group-plan"><h3>${escapeHtml(sess.title)}</h3><div class="small">${escapeHtml(cycle.description)}</div><div class="group-block"><b>Objetivos</b><ul class="steps">${sess.goals.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div><div class="group-block"><b>Estructura orientativa · 60 min</b><ol class="steps"><li><b>Apertura (5 min):</b> check-in breve y encuadre.</li><li><b>Recuperación (5 min):</b> recordar una idea de la sesión previa.</li><li><b>Psicoeducación (10 min):</b> ${escapeHtml(sess.teach)}</li><li><b>Ejercicio (25 min):</b> ${escapeHtml(sess.exercise)}</li><li><b>Puesta en común (10 min):</b> aprendizaje y aplicación.</li><li><b>Cierre (5 min):</b> ${escapeHtml(sess.task)}</li></ol></div>${adaptations.length?`<div class="group-block"><b>Adaptación sugerida</b><ul class="steps">${adaptations.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul></div>`:''}<div class="group-block"><b>Fuentes</b>${groupSourceHtml(sess.sources)}</div><div class="notice warn" style="margin-top:10px">Evitar contenido individual identificable o situaciones de riesgo agudo en el histórico grupal. Las necesidades individuales se documentan por los cauces clínicos autorizados.</div></div>`;
}
function getGroupHistory(){try{const h=JSON.parse(localStorage.getItem('psikiaGroupHistory')||'[]');return Array.isArray(h)?h:[]}catch{return []}}
function renderGroupHistory(){
 const h=getGroupHistory();
 $('#groupHistory').innerHTML=h.length?h.slice().reverse().map((x,rev)=>{const real=h.length-1-rev;return `<div class="group-history-item"><div class="meta">${escapeHtml(x.date)} · ${escapeHtml(x.cycle)}</div><strong>${escapeHtml(x.session)}</strong><div class="small" style="margin-top:5px;white-space:pre-wrap">${escapeHtml(x.feedback)}</div><div class="therapy-actions"><button class="secondary" data-load-group="${real}">Usar para adaptar siguiente</button><button class="danger" data-delete-group="${real}">Eliminar</button></div></div>`}).join(''):'<p class="small">Todavía no hay sesiones guardadas.</p>';
 $$('[data-load-group]').forEach(b=>b.addEventListener('click',()=>{const x=getGroupHistory()[Number(b.dataset.loadGroup)];if(!x)return;$('#groupTone').value=x.feedback;renderGroupPrivacy(x.feedback,'#groupPrivacy');showTab('grupo');window.scrollTo({top:0,behavior:'smooth'});}));
 $$('[data-delete-group]').forEach(b=>b.addEventListener('click',()=>{const h=getGroupHistory();h.splice(Number(b.dataset.deleteGroup),1);localStorage.setItem('psikiaGroupHistory',JSON.stringify(h));renderGroupHistory();}));
}
function saveGroupFeedback(){
 const feedback=$('#groupFeedback').value.trim();if(!feedback)return alert('Escribe un resumen global de cómo fue la sesión.');
 const hits=renderGroupPrivacy(feedback,'#groupFeedbackPrivacy');if(hits.length)return alert('No guardar: revisa posibles datos identificables o seudonimizados. Resume solo la dinámica global.');
 const c=groupCycles[$('#groupCycle').value]||groupCycles.mixed;const i=Number($('#groupSession').value)||0;const ss=c.sessions[i];
 const h=getGroupHistory();h.push({date:new Date().toLocaleDateString('es-ES'),cycle:c.name,cycleId:$('#groupCycle').value,session:ss.title,sessionIndex:i,feedback:feedback.slice(0,4000)});while(h.length>60)h.shift();localStorage.setItem('psikiaGroupHistory',JSON.stringify(h));$('#groupFeedback').value='';renderGroupPrivacy('','#groupFeedbackPrivacy');renderGroupHistory();alert('Feedback grupal guardado localmente.');
}
function chooseNextGroupSession(){
 const h=getGroupHistory();if(h.length){const last=h[h.length-1];if(groupCycles[last.cycleId]){$('#groupCycle').value=last.cycleId;populateGroupSessions();const max=groupCycles[last.cycleId].sessions.length;$('#groupSession').value=String((Number(last.sessionIndex)+1)%max);$('#groupTone').value=last.feedback||'';renderGroupPrivacy($('#groupTone').value,'#groupPrivacy');buildGroupPlan();return;}}
 $('#groupCycle').value='mixed';populateGroupSessions();$('#groupSession').value='0';buildGroupPlan();
}
function groupHistoryText(){return getGroupHistory().map(x=>`${x.date} — ${x.cycle} — ${x.session}\n${x.feedback}`).join('\n\n')}
$('#groupCycle').addEventListener('change',()=>{populateGroupSessions();currentGroupPlanText='';$('#groupPlan').innerHTML='<p class="small">Selecciona la sesión y pulsa “Preparar sesión”.</p>'});
$('#groupTone').addEventListener('input',e=>renderGroupPrivacy(e.target.value,'#groupPrivacy'));
$('#groupFeedback').addEventListener('input',e=>renderGroupPrivacy(e.target.value,'#groupFeedbackPrivacy'));
$('#buildGroupSession').addEventListener('click',buildGroupPlan);
$('#randomGroupSession').addEventListener('click',chooseNextGroupSession);
$('#copyGroupPlan').addEventListener('click',async()=>{if(!currentGroupPlanText)return alert('Prepara primero una sesión.');try{await navigator.clipboard.writeText(currentGroupPlanText);alert('Guion copiado.')}catch{alert(currentGroupPlanText)}});
$('#saveGroupFeedback').addEventListener('click',saveGroupFeedback);
$('#clearGroupFeedback').addEventListener('click',()=>{$('#groupFeedback').value='';renderGroupPrivacy('','#groupFeedbackPrivacy')});
$('#copyGroupHistory').addEventListener('click',async()=>{const t=groupHistoryText();if(!t)return alert('No hay histórico.');try{await navigator.clipboard.writeText(t);alert('Histórico copiado.')}catch{alert(t)}});
$('#clearGroupHistory').addEventListener('click',()=>{if(confirm('¿Borrar todo el histórico grupal local?')){localStorage.removeItem('psikiaGroupHistory');renderGroupHistory();}});
populateGroupCycles();renderGroupPrivacy('','#groupPrivacy');renderGroupPrivacy('','#groupFeedbackPrivacy');renderGroupHistory();

const resources=[['Centro de Salud Mental (CSM)','Seguimiento comunitario multiprofesional y coordinación.'],['Unidad de Rehabilitación','Intervención intensiva rehabilitadora y funcional.'],['Hospital de Día','Hospitalización parcial para cuadros agudos/subagudos.'],['Equipos sociocomunitarios','Apoyo domiciliario/comunitario, AVD y adherencia.'],['CRPS y recursos rehabilitadores','Autocuidado, habilidades, actividad, integración comunitaria.'],['ANASAPS y tercer sector','Apoyo social, ocupacional, familiar y comunitario según disponibilidad/localización.'],['Recursos residenciales','Apoyo graduado de alojamiento según autonomía.'],['Inserción laboral / empleo con apoyo','Objetivos ocupacionales y retorno progresivo al empleo.']];
$('#resources').innerHTML=resources.map(([a,b])=>`<div class="suggestion"><strong>${escapeHtml(a)}</strong><div class="small">${escapeHtml(b)}</div></div>`).join('');

$('#analyze').addEventListener('click',()=>{const text=$('#raw').value.trim();if(!text)return alert('Introduce o dicta contenido primero.');const hits=privacyScan(text);if(hits.length&&$('#blockOnIdentifiers').checked)return alert('Se han detectado posibles identificadores. Revísalos antes de continuar.');const type=$('#tipo').value;currentSections=templates[type].sections;currentReport=buildReport(text,type);lastSourceText=text;renderReport();renderClinicalControl(text);renderTherapy(text);showTab('informe')});
$('#clear').addEventListener('click',()=>{if(confirm('¿Borrar la nota actual?')){$('#raw').value='';currentReport={};currentSections=[];lastSourceText='';$('#reportSections').innerHTML='<p class="small">Aún no hay informe.</p>';updatePrivacy()}});
$('#copyReport').addEventListener('click',async()=>{const t=reportText();if(!t.trim())return;try{await navigator.clipboard.writeText(t);alert('Informe copiado.')}catch{alert(t)}});
$('#shareReport').addEventListener('click',async()=>{const t=reportText();if(navigator.share){try{await navigator.share({title:$('#subjectPrefix').value,text:t})}catch{}}else{try{await navigator.clipboard.writeText(t);alert('Informe copiado.')}catch{}}});
$('#emailReport').addEventListener('click',()=>{const t=reportText(),hits=privacyScan(t);if(hits.length&&$('#blockOnIdentifiers').checked)return alert('Envío bloqueado: revisa posibles identificadores.');const to=$('#email').value.trim();if(!to)return alert('Configura el correo profesional.');const subject=encodeURIComponent(`${$('#subjectPrefix').value} - ${templates[$('#tipo').value].label}`), body=encodeURIComponent(t);location.href=`mailto:${encodeURIComponent(to)}?subject=${subject}&body=${body}`});

function makeContextSummary(){if(!currentSections.length)return '';const preferred=['Motivo de consulta / derivación','Antecedentes psiquiátricos personales','Situación sociolaboral y funcional','Tratamiento farmacológico actual','Juicio clínico / diagnóstico','Resumen clínico longitudinal','Evolución / enfermedad actual','Juicio clínico'];const chunks=[];preferred.forEach(k=>{if(currentReport[k])chunks.push(currentReport[k])});if(!chunks.length)chunks.push(reportText().slice(0,3500));return uniqueJoin(chunks).slice(0,5000)}
function renderContext(){const c=getContext();$('#contextPreview').textContent=c?.summary||'No hay contexto longitudinal guardado.'}
$('#saveContext').addEventListener('click',()=>{const s=makeContextSummary();if(!s)return alert('Primero genera y revisa un informe.');if(privacyScan(s).length)return alert('El contexto contiene posibles identificadores. Revísalo antes de guardarlo.');localStorage.setItem('psikiaContext',JSON.stringify({summary:s,updated:new Date().toISOString()}));renderContext();alert('Contexto longitudinal guardado localmente.')});
$('#clearContext').addEventListener('click',()=>{localStorage.removeItem('psikiaContext');renderContext()});renderContext();

$('#saveSettingsBtn').addEventListener('click',()=>{localStorage.setItem('psikiaSettings',JSON.stringify({email:$('#email').value.trim(),subject:$('#subjectPrefix').value.trim()}));alert('Ajustes guardados localmente.')});
(function loadSettings(){try{const s=JSON.parse(localStorage.getItem('psikiaSettings')||'{}');$('#email').value=s.email||'Alejandro.ballesteros.prados@navarra.es';$('#subjectPrefix').value=s.subject||'Borrador clínico Psikia Hub'}catch{}})();

let recognition=null;
$('#dictate').addEventListener('click',()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert('Este navegador no ofrece reconocimiento de voz web. Puedes usar el dictado del teclado del móvil.');if(recognition){recognition.stop();return}if(!confirm('El reconocimiento de voz puede usar servicios del proveedor del dispositivo/navegador. Continúa solo si está autorizado por tu organización.'))return;recognition=new SR();recognition.lang='es-ES';recognition.continuous=true;recognition.interimResults=true;let base=$('#raw').value;recognition.onresult=e=>{let final='',inter='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript+' ';else inter+=e.results[i][0].transcript+' '}if(final){base+=(base?' ':'')+final;$('#raw').value=base;updatePrivacy()}else $('#raw').value=base+(base?' ':'')+inter};recognition.onend=()=>{recognition=null;$('#dictate').textContent='🎙️ Dictar';updatePrivacy()};recognition.onerror=()=>{recognition=null;$('#dictate').textContent='🎙️ Dictar'};recognition.start();$('#dictate').textContent='⏹️ Parar'});

if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
